.gitignore, package.json, yarn.lock
**What**  
Fixed Storybook, it is currently failing.
The problem was related to `frontend-govuk` fonts failing to load.
```
ERROR in ./stylesheets/all.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--14-2!./stylesheets/all.scss)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '/assets/fonts/light-94a07e06a1-v2.woff2' in '/Users/luca/dev/hackney/lbh-social-care/stylesheets'
```
`frontend-govuk` library is directly referencing fonts contained in `node_modules/govuk-frontend/govuk/assets/` and it is supposing that they are in a `assets` folder in the root of the repo (see their [DOC](https://frontend.design-system.service.gov.uk/get-started/#4-get-the-font-and-images-working) for more info. 
As we are not using …
=> fixed storybook

utils/server/residents.js, utils/server/residents.spec.js
**What**  
Now also the `getResidents` APIs are using the mosaic endpoint.
=> Use mosaic endpoints for all the residents APIs

utils/server/residents.js, utils/server/residents.spec.js
**What**  
**cases** APIs moved from `/residents/cases` to `/cases` 🤷
=> aligned cases APIs to the server

components/FormWizard/FormWizard.jsx, utils/steps.jsx, utils/steps.spec.jsx
**What**  
Fixed issue related to #55.
**The loogic behind it:**
After being redirect to a step from the summary, if the step answers are going to change the visible steps the next is not redirecting to the summary itself but is continuing to the normal flow of the form.
- I created a branch for easy testing this `feature/multi-step-test`
- go to `/form/multi-step/step-a`
- on first step select **No**
- once in the summary go back to change the first step
- select **Yes**
- check that now you are going to **step b** instead of the summary
=> fixed changes from summary on conditional step

components/Search/Search.jsx, cypress/integration/search_by_name_adult_admin.js, cypress/integration/search_by_name_children_admin.js, pages/api/cases/index.js, pages/api/residents/[id]/cases.js, pages/api/residents/index.js
**What**  
Our API layer was returning 404 if a record was `[]`.
```
{
"residents": [],
"nextCursor": ""
}
```
Now it's returning `[]`, instead of triggering an error.
=> refactored APIs to not return empty record array as 404

components/Cases/Cases.jsx, components/Cases/CasesTable.jsx, components/Cases/CasesTable.spec.jsx, components/Search/results/CasesTable.jsx, components/Search/results/CasesTable.spec.jsx, pages/api/residents/[id]/cases.js, utils/api/cases.js, utils/api/cases.spec.js, utils/api/residents.js, utils/api/residents.spec.js, utils/server/cases.js, utils/server/cases.spec.js
**What**  
- Used `dateOfEvent` instead of `caseFormTimestamp` for cases
- Fixed proptypes error for casesTable
- `getResidentCases` was move from `utils/api/residents` to `utils/api/cases` and renamed `getCasesByResident`
=> Fixed cases date default sorting

components/Form/DatePicker/DatePicker.jsx, components/Form/Radios/Radios.jsx, components/Form/Select/Nationality.jsx, components/Form/Select/Select.jsx, components/Form/TextInput/TextInput.jsx, components/Summary/Summary.jsx
**What**
It's now possible defining `Radios` components as:
```
{
component: 'Radion',
name: 'gender',
label: 'Gender',
options: [
{ value: 'F', text: 'Female' },
{ value: 'M', text: 'Male' },
{ value: 'U', text: 'Unknown' },
{ value: 'I', text: 'Indeterminated' },
],
},
```
**Plus**
- Fixed how dates appear in summary (from `yyyy-mm-dd` to `dd-mm-yyyy`)
- Fixed Select visual required feedback
- Fixed conditional rendering of the required feedback
=> Radio can now have key/values options

components/Form/AddressLookup/AddressLookup.jsx, components/Form/DateInput/DateInput.jsx
**What**  
- prevent annoying warning message of uncontrolled controller (see [this discussion](https://github.com/react-hook-form/react-hook-form/discussions/3653) for more info)
- fixed dateInput ref (on error it should focus on the date input)
- force the date year to 4 digits (preventing `12-21-13` to be flag as valid date)
=> Improvements on DateInput

components/Search/results/CasesTable.jsx, utils/date.js, utils/date.spec.js
**What**  
Currently, the cases search is breaking if `dateOfEvent` is null.
We will check that the date is valid before formatting it.
=> prevent search cases to break if dateOfEvent is null

.env.sample, components/Search/forms/SearchResidentsForm.jsx, pages/api/residents/[id]/index.js, serverless.yml, utils/server/residents.js, utils/server/residents.spec.js
**What**  
- removed check that must be a number
- used cases API endpoint for resident
- mapped getResident on getResidents (so we can just use one endpoint)
=> removed check that must be a number and used only one endpoint

components/Form/DateInput/DateInput.jsx, components/Search/forms/SearchCasesForm.jsx
**What**  
- `DateInput` now supports EU format of the date
- the search by cases is now searching by EU date format
**Note**
This is an interim work, the date should (hopefully soon) be always defined in ISO format.
=> support EU format for date

components/Cases/CasesTable.jsx, components/Cases/__snapshots__/CasesTable.spec.jsx.snap, components/Search/results/CasesTable.jsx, components/Search/results/__snapshots__/CasesTable.spec.jsx.snap
**What**  
- hide the `view` link is not present in the cases
- this is solving the problem of the user being bounced to the top of the page if the URL is not there
=> only show view on cases if present

components/AllocatedWorkers/AllocatedWorkers.jsx, components/Cases/Cases.jsx, components/ErrorMessage/ErrorMessage.jsx, components/ErrorMessage/ErrorMessage.spec.jsx, components/ErrorMessage/__snapshots__/ErrorMessage.spec.jsx.snap, components/Form/AddressLookup/AddressLookup.jsx, components/PersonView/PersonView.jsx, components/Search/Search.jsx, components/Search/Search.spec.jsx, pages/api/cases/index.js, pages/api/postcode/[postcode].js, pages/api/residents/[id]/allocated-workers.js, pages/api/residents/[id]/cases.js, pages/api/residents/[id]/index.js, pages/api/residents/index.js
**What**  
When API is failing is returning an error with `{message: "internal server error"}` this is mimic the same behaviour in our API layer plus it's preventing the FE to fail (because it's trying to set an object as react child.
Also, show a generic error message, the user doesn't need to know what's wrong with the APIs.
=> wrapped API message error in a object aligned with aws

__mocks__/react-modal.js, components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.jsx, components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.spec.jsx, components/AllocatedWorkers/AddAllocatedWorker/__snapshots__/AddAllocatedWorker.spec.jsx.snap, components/AllocatedWorkers/AllocatedWorker.spec.jsx, components/AllocatedWorkers/AllocatedWorkers.jsx, components/Modal/Modal.module.scss, components/Modal/Modal.spec.jsx, components/Modal/__snapshots__/Modal.spec.jsx.snap, pages/api/residents/[id]/allocated-workers.js, pages/api/teams/[team_id]/workers.js, pages/api/teams/index.js, stylesheets/all.scss, utils/api/allocatedWorkers.js, utils/api/allocatedWorkers.spec.js, utils/server/allocatedWorkers.js, utils/server/allocatedWorkers.spec.js, utils/server/teams.js, utils/server/teams.spec.js, utils/server/workers.js, utils/server/workers.spec.js
**What**  
- Added functionality for **allocate workers**
- Added the following endpoints
- `/api/teams`
- `/api/teams/:teamId/workers`
- `POST /api/residents/:residentId/allocated-workers`
- Improved look&feel of the modal
- Improved `react-modal` mock
**Notes**
- the `POST` API is not there yet
- at the moment is only visible for Admin users (the proper user group is going to be introduced by #121)
=> Add allocated worker

components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.jsx
**What**  
In case of API failing it was rendering fewer hooks breaking the page.
See more details [here](https://reactjs.org/docs/error-decoder.html/?invariant=300).
=> fixed problem with fewer hooks rendered

components/Search/Search.jsx, components/Search/Search.spec.jsx, components/Search/forms/SearchCasesForm.jsx, components/Search/forms/SearchCasesForm.spec.jsx, components/Search/forms/SearchResidentsForm.jsx, components/Search/forms/SearchResidentsForm.spec.jsx, pages/cases/index.jsx, pages/index.jsx, utils/urls.js, utils/urls.spec.js
**What**  
- removed `useEffect` from the search forms, centralized it in the parent search component
- form search and sort are using the same logic
- merged the `sort` and the `query` object
- not need to store in the component `formData` and `sort`
- not need to populate the query server side
**How to test it?**
Everything should work as before
=> Centralized the search around the router query

components/DynamicStep/DynamicStep.jsx
**What**  
Decoupled **Save and Exit** from the form submission. Now it's possible to save uncompleted forms (even if they are not valid) this is making the save functionality useful also for single-page forms.
- go to http://localhost:3000/form/test/first-step
- select *show next step*
- then *save and exit*
- check that is working properly
=> fixed saving functionality

components/AllocatedWorkers/AllocatedWorkers.jsx, components/AllocatedWorkers/AllocatedWorkers.spec.jsx, components/AllocatedWorkers/AllocatedWorkersTable.jsx
**What**  
- Used `hasAllocationsPermissions` for show/hide allocation interactions
- Fixed propTypes in `AllocatedWorkerTable` component
- Fixed spec filename
=> used hasAllocationsPermissions instead of hasAdminPermissions

utils/server/allocatedWorkers.js, utils/server/allocatedWorkers.spec.js
**What**  
Filter allocations if _status_ is **closed** or _end data_ is in the **past**.
Note: as there are leftovers of the old import the `caseStatus` can be `Closed` or `closed`.
- check that `people/234` doesn't have any allocation
=> filtering allocation if end date is in the past or closed

components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.jsx, components/Modal/Modal.jsx, components/Modal/Modal.module.scss, components/Modal/Modal.spec.jsx, stylesheets/all.scss
**What**  
- fixed modal scrolling (when the content of the modal is bigger than view height)
- prevent scroll of the body, behind the modal
- in `AddAllocatedWorkers` fixed jump when loading a different team, setting the current workers as `disabled`
The `govuk` library is setting 
```
.govuk-template {
overflow-y: scroll;
}
```
on the `html`, as I am not sure of the reason behind it I am setting the `overflow` of the `html` to `hidden` when the modal is open.
=> fixed modal scrolling

components/Form/DateInput/DateInput.jsx, components/Search/forms/SearchCasesForm.spec.jsx, components/Search/forms/SearchResidentsForm.spec.jsx, utils/date.js, utils/date.spec.js
**What**  
- made the `DateInput` component (used by the `ControlledDateInput`) uncontrolled, this is making the component resettable and it's avoiding a bunch of conflicts related to the control of the inputs
- moved out `stringDateToObject` and `objectDateToString` and added to the `utils/date`
- improved `parseDate` util
- check that the _day_ and _month_ are two digits, as 1 digit is not returning any result
Please double-check that the component is working as expected
=> made the DateInput component uncrontrolled

lambda.js, package.json, yarn.lock
**What**  
The lambda is returning the `body` as a Buffer, as we added validation for `POST` the validator is failing if we don't have a valid object.
This PR is fixing that problem.
=> added bodyParser to the /api route

components/FormWizard/DynamicInput.jsx, components/FormWizard/DynamicStep.jsx, components/Summary/Summary.jsx, cypress/integration/form.js, data/forms/test.jsx
**What**  
It's now possible to pass a function to `options` in the form definition. The function will get the current form data as the first argument, in this way we can deal with inputs with options depending to other inputs (i.e. `ethnicity/sub-ethnicity`).
- go to http://dev.hackney.gov.uk:3000/form/test/first-step
- select **Show multi-select step**
- check that is working properly
=> added support for dynamic options prop

components/Form/DateInput/DateInput.jsx
**What**  
Fixed mising `format` for `objectDateToString`.
- check `/cases`
- the date should work as expected
=> fixed missing format on DateInput

components/AllocatedWorkers/AllocatedWorkersTable.jsx, components/AllocatedWorkers/AllocatedWorkersTable.spec.jsx, components/AllocatedWorkers/DeallocateWorkerDetails/DeallocatedWorkerDetails.jsx
**What**  
Removes the unneeded prop of `personName` from the `AllocatedWorkersTable` component and adds the missing prop types of `id` and `personId` to the `records` attribute and the `updateWorkers` function prop to the list of required prop types
**Why**  
To better reflect what props are actually needed for the component
Forgive the confusing branch name, this PR is supposed to just rectify the missing props from the component
=> Fix props for allocation table

components/FormWizard/DynamicInput.jsx, data/forms/create-new-person.jsx
**What**  
- probably was lost during some merge conflicts 🤷 
- added a custom error when the component is not found
**Before:**
**After:**
or
=> added missing component type

components/Form/ObjectInput/ObjectInput.jsx, components/Form/ObjectInput/ObjectInput.module.scss, components/Form/ObjectInput/ObjectInput.spec.jsx, components/Form/ObjectInput/__snapshots__/ObjectInput.spec.jsx.snap, components/FormWizard/DynamicInput.jsx, components/FormWizard/DynamicInputMulti.jsx, components/FormWizard/DynamicInputMulti.module.scss, components/FormWizard/DynamicInputMulti.spec.jsx, components/FormWizard/DynamicStep.jsx, components/FormWizard/FormWizard.jsx, components/FormWizard/__snapshots__/DynamicInputMulti.spec.jsx.snap, components/Summary/Summary.jsx, data/forms/create-new-person.jsx, data/forms/test.jsx, docs/formBuilder/03-FormComponents.stories.mdx, utils/__snapshots__/summary.spec.jsx.snap, utils/summary.jsx, utils/summary.spec.jsx
**What**  
- simplified the `DynamicInput`
- introduced the `DynamicInputMulti` that is taking care of add multiple instances of the same input
- extracted the summary formatting login in an ad-hoc component `utils/summary` and added test coverage
- fixed `ObjestInput` test
- Reverted "removed summaryInline from the props"
- added phone number in `create-person` form
- small style tweaks
**How is working**
Every input now support `isMulti` and `isMultiTrigger`
```
{
component: 'Object',
name: 'phone_number',
label: 'Phone Number',
isMulti: true,
components: [
{
component: 'PhoneInput',
name: 'phoneNumber',
label: 'Phone number',
rules: { required: true },
},
{
component: 'TextInput',
name: 'phoneType',
label: 'Phone type',
},
],
},
```
is returning:
```
[
{
phoneType: "main contact", …
```
=> Added support for `isMulti` to the form components

components/AddForm/AddForm.jsx, components/AddForm/AddForm.spec.jsx, components/PersonView/PersonView.jsx, components/PersonView/PersonView.spec.jsx, pages/people/[id]/records.jsx
**What**  
- removed `getResident` from `AddForm` and passed it down from `PersonView`
- `PersonView` supports children as `node` and `func` (with render prop)
**Details**
At the moment the `AddForm` component is waiting that the `getPerson` in `PersonView` is finished to rerun the same call. We can show the `AddForm` component as soon as the first call is completed.
**How to test it?**
- check that `/people/:id/records` is working properly
=> Refactored `AddForm` to use the getResident results from the parent

components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.jsx, components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.spec.jsx, components/AllocatedWorkers/AddAllocatedWorker/__snapshots__/AddAllocatedWorker.spec.jsx.snap, components/AllocatedWorkers/AllocatedWorkers.jsx, components/AllocatedWorkers/AllocatedWorkers.spec.jsx, components/AllocatedWorkers/AllocatedWorkersTable.jsx, components/AllocatedWorkers/AllocatedWorkersTable.spec.jsx, components/AllocatedWorkers/DeallocateWorker/DeallocateWorker.jsx, components/AllocatedWorkers/__snapshots__/AllocatedWorkersTable.spec.jsx.snap, pages/people/[id]/allocations/[allocationId]/remove.jsx, pages/people/[id]/allocations/add.jsx
- extracted add allocations in a stand alone page (`/people/:id/allocations/add`)
- extracted delete allocations in a stand alone page (`/people/:id/allocations/:allocationId/remove`)
**Note:**
- The APIs at the moment are failing, they will be addressed in a next PR when the BE will be ready
=> extracted allocation logic in stand alone pages

components/Search/Search.jsx, components/UserContext/UserContext.jsx, pages/_app.jsx, utils/auth.js, utils/user.js
**What**  
A check is made on page rendering and if it's the case, redirect.
This is fixing the use of `UserContext` in not logged pages.
Used `hasAdminPermissions` instead of `getUserType` on `Search`.
Also, added documentation for `getUserType`.
=> added redirect to ssr if not authenticated

components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.jsx, components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.spec.jsx, pages/api/teams/index.js, pages/people/[id]/allocations/add.jsx, utils/api/allocatedWorkers.js, utils/api/allocatedWorkers.spec.js
**What**  
Currently we are showing teams based on the user context, we need to show them based on the resident `ageContext` instead.
- check a child resident http://dev.hackney.gov.uk:3000/people/321569/allocations/add
- check an adult resident http://dev.hackney.gov.uk:3000/people/234/allocations/add
- they need to show different teams
=> pass age context to the getTeams in add allocations

components/Cases/Cases.spec.jsx, components/Cases/CasesTable.jsx, components/Cases/__snapshots__/Cases.spec.jsx.snap, utils/date.js, utils/date.spec.js
**What**
- improved sanitisation of the date
supported syntax:
```
22/09/1941
22/01/2021 10:46:42
2000-12-12
2021-01-19T16:28:54.1295896Z
```
- fallback to `caseFormTimestamp` if `dateOfEvent` is not present
It's not ideal using regex for extract dates but until the BE is not fixing this it's good enough.
=> fall back to timestamp if no date if event

components/AllocatedWorkers/AllocationRecap/AllocationRecap.jsx, components/AllocatedWorkers/AllocationRecap/AllocationRecap.spec.jsx, components/Cases/CaseLink.jsx, utils/server/cases.js
**What**  
- added possibility to view the allocation records
- fixed the `getCase` if the allocation/deallocation is not in the first 20 records returned (this is going to be fixed when the BE will release a direct get)
Check http://dev.hackney.gov.uk:3000/people/33343831 as it has allocations and deallocations.
=> properly show the allocation/deallocation page, based on the record

components/Search/Search.jsx, components/Search/Search.spec.jsx, components/Search/forms/SearchCasesForm.jsx, components/Search/forms/SearchCasesForm.spec.jsx
**What**  
**Note**
if `Only include records I've created` is selected this has the precedence over `worker_email`
=> added search for worker email to case search

components/FormWizard/FormWizard.jsx, components/Steps/Confirmation.jsx, components/Steps/Summary.jsx, components/Steps/__snapshots__/Confirmation.spec.jsx.snap, components/Steps/__snapshots__/Summary.spec.jsx.snap, components/Summary/Summary.jsx, components/Summary/Summary.module.scss, components/Summary/Summary.spec.jsx, components/Summary/__snapshots__/Summary.spec.jsx.snap, cypress/integration/form.js, stylesheets/all.scss, utils/objects.js, utils/objects.spec.js, utils/summary.jsx, utils/summary.spec.jsx
**What**  
Added collapse/expand functionality to the summary component
Behaviour:
```
no collapsed section -> collapse all
1 or more section collapsed -> expand all
```
`FormWizard` supports `isSummaryCollapsable` default `true` for forms with more than 1 step.
- Check the `/form/test`
=> added collapse/expand functionality to the summary component

package.json, pages/people/[id]/case-notes-recording/[[...stepId]].jsx, utils/server/cases.js, utils/server/cases.spec.js, yarn.lock
**What**  
Fixed `POST /cases`
We are passing all the meaningful information inside the `caseFormData`.
```
{
caseFormData: `{"timestamp":"2021-02-19T16:02:27.325Z","worker_email":"asd@hackney.gov.uk","context_flag":"A","form_name":"Manager's Decision","mosaic_id":"234","first_name":"John","last_name":"Doe","date_of_event":"2000-10-01"}`
}
```
Added `mockdate` module for testing dates.
- go to `people/:id/case-notes-recording`
- add a case note
- check that has been populated correctly
=> fixed case notes post

components/Form/AddressLookup/AddressLookup.jsx, components/Form/AddressLookup/AddressLookup.spec.tsx, cypress/integration/form.js, data/forms/test.jsx
**What**
- fixed validation if not required
At the moment it's asking for a valid postcode even if not required
- added address lookup to the test form
- added address lookup in test form
=> fix address lookup validation

pages/people/[id]/allocations/[allocationId]/remove.tsx, pages/people/[id]/allocations/add.tsx
**What**  
A user that is not part of the allocators group won't be able to access `/person/:id/allocations/add` and `/person/:id/allocations/:allocationId/remove`
- try to navigate to the addresses listed above as user without `hasAllocationsPermissions` and see that you are going to be redirected to the person page
- try to do the same but with a user with `hasAllocationsPermissions` and it should work as before
=> only allow to access add and removed url if part of the correct user group

components/FormWizard/FormWizard.jsx, components/Layout/Seo/Seo.spec.tsx, components/Layout/Seo/Seo.tsx, components/Layout/Seo/__snapshots__/Seo.spec.tsx.snap, components/Layout/index.jsx, next-seo.config.js, package.json, pages/_app.jsx, pages/access-denied.jsx, pages/cases/index.jsx, pages/index.jsx, pages/login.jsx, pages/people/[id]/allocations/[allocationId]/index.jsx, pages/people/[id]/allocations/[allocationId]/remove.tsx, pages/people/[id]/allocations/add.tsx, pages/people/[id]/case-notes-recording/[[...stepId]].tsx, pages/people/[id]/index.jsx, pages/people/[id]/records/conversation-1/[[...stepId]].tsx, pages/people/[id]/records/index.jsx, pages/workers/[id]/index.jsx, yarn.lock
**What**  
- Removed third-party module `next/seo` in favour of the native `next/head` (https://nextjs.org/docs/api-reference/next/head)
- `next-seo` was roughtly 7kb gzip according to bundlephobia https://bundlephobia.com/result?p=next-seo@4.20.0
- `noidex` is already been covered by https://github.com/LBHackney-IT/lbh-social-care/blob/main/public/robots.txt
Page titles should work as before
=> removed next/seo, used next/head instead

components/Cases/CasesTable.jsx, components/Cases/__snapshots__/Cases.spec.jsx.snap, components/Search/results/CasesTable.jsx
**What**  
At the moment the BE is returning cases sorted in 2 groups, the first one by `dateOfEvent` and if it's not present by `caseFormTimestamp`. This is leading to some confusion in the UI.
This should be rolledback once the BE is merging the two sorting.
=> hide caseFormTimestamp from cases

utils/server/residents.spec.ts, utils/server/residents.ts
**What**  
If the user inserts a number but not the type the form is valid but the BE breaks.
This is a temporary quick fix as production is broken.
- create a new person and as a phone number specify the number but not the type.
=> initialise phoneNumber type as main if not present

pages/api/residents/[id]/warning-notes/index.ts, types.ts, utils/server/warningNotes.ts
**What**  
Mocked BE for warning notes.
In order to enable this mock the following env variable is needed `MOCKED_WARNING_NOTES=true`.
The new endpoint is `/api/residents/:residentId/warning-notes`.
There are 3 possible returns, based on the rest of the operation (`personId` / 3):
- if the rest is `0` it returns `[]`
- if the rest is `1` it returns
```
[
{
"id": 123,
"type": "Risk to Adults",
"createdDate": "2021-01-12T00:00:00.000Z",
"createdBy": "Foo",
"reviewsDate": "2021-01-13T00:00:00.000Z",
"reviewsBy": "Bar"
}
]
```
- if the rest is `2` it returns:
```
[
{
"id": 123,
"type": "Risk to Adults",
"createdDate": "2021-01-12T00:00:00.000Z",
"createdBy": "Foo",
"reviewsDate": "2021-01-13T00:00:00.000Z",
"reviewsBy": "Bar"
},
{
"id": 234,
"type": "Risk to Staff",
"createdDate": …
```
=> mocked getWarningNotes

components/ExpandDetails/ExpandDetails.module.scss, components/ExpandDetails/ExpandDetails.spec.tsx, components/ExpandDetails/ExpandDetails.stories.tsx, components/ExpandDetails/ExpandDetails.tsx, components/ExpandDetails/__snapshots__/ExpandDetails.spec.tsx.snap
**What**  
Expand the html `details` element https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details 
- run storybook `yarn storybook`
- check the new component http://192.168.0.2:6006/?path=/story/expanddetails--default
=> added show details component

data/forms/warning-note.tsx, pages/people/[id]/warning-notes/add/[[...stepId]].tsx
**What**  
Added warning note form for Adult and Child
Ad the Child form is the same as the Adult but without _WARNING_DISCLOSURE_, I created a block per each section and then merged them in the Step definition, instead of duplicating the whole form definition.
**How to test it**  
Go to `/people/:peopleId/warning-notes/add`
**What is missing**
- Improving spacing in the page
- What to do about the line rendered on conditional question
- Check on dates (start date / end date should be validated together, this is going to be fun)
- Changes on copy on Summary / Confirmation, I would keep as generic as possible at the moment, we can see if we can push them back or find a generic labeling, but this PR focused only on the form itself
=> added warning note form

serverless.yml
**What**  
We reached the maximum size of the lambda storage.
This change will prevent to create a new version each deploy.
=> removed versioning of the lambda

components/Form/DateInput/DateInput.tsx, components/Form/types.ts, components/FormWizard/DynamicInput.jsx
**What**  
Extended `rules.validation` in the FormSteps components.
At the moment it's accepting just the value of the input, with the `currentData`, so we can validate inputs based on other inputs.
Fixed the validation of `DateInput`. 
Validation can be either a `function` or an `object`, at the moment `DateInput` was accepting only objects.
Add the following components to a step, if date 2 is before date 1 it should fail:
```
{
component: 'DateInput',
name: 'date1',
label: 'first date',
},
{
component: 'DateInput',
name: 'date2',
label: 'second date',
rules: {
validate: (value, { date1 }) =>
new Date(date1)?.getTime() > new Date(value)?.getTime() || 'Nope',
},
},
```
=> improved validation

components/AllocatedWorkers/AllocationRecap/AllocationRecap.jsx, components/AllocatedWorkers/AllocationRecap/AllocationRecap.spec.jsx, components/Cases/CaseRecap/CaseRecap.jsx, components/Cases/CaseRecap/CaseRecap.spec.jsx, lib/cases.ts, pages/api/cases/[caseId].ts, pages/people/[id]/records/[recordId]/index.tsx, utils/api/cases.spec.ts, utils/api/cases.ts
**What**
- used proper backend endpoint for getCase, removed terrible hack
- fixed layout
- fixed types for `caseId`
- added missing unit test
Refactored `getCase` endpoint:
`/api/residents/:residentId/cases/:caseId` to `/api/cases/:caseId` as we don't need the `residentId`
- check that `http://dev.hackney.gov.uk:3000/people/234/records/602fb668890134f6e767161f` is working properly
- check that `http://dev.hackney.gov.uk:3000/api/cases/602fb668890134f6e767161f` is working properly
=> fixed get case endpoint

components/Form/types.ts, data/forms/warning-note.tsx
**What**  
- Fixed types for `rules`, supporting both scenarios
```
{ 
validate: // validation logic
}
```
and
```
{
validate: {
firstValidation: // validation logic
secondValidation: // validation logic
}
}
```
- Added validation for `end date`, checks that it's not more than 1 year apart and it's not in the past, compared to the start date.
- go to `/people/234/warning-notes/add`
- test start date / end date
=> fixed types for rules

components/Cases/CaseRecap/__snapshots__/CaseRecap.spec.jsx.snap, components/Summary/Summary.module.scss, components/Summary/Summary.stories.jsx, components/Summary/SummaryList.spec.tsx, components/Summary/SummaryList.tsx, components/Summary/__snapshots__/SummaryList.spec.tsx.snap, components/WarningNote/WarningNoteRecap/__snapshots__/WarningNoteRecap.spec.tsx.snap, utils/__snapshots__/summary.spec.jsx.snap, utils/summary.jsx
**What**  
- the `TextArea` value is not being wrapped by a `<pre>` element, so it maintains the formatting
- spin storybook
- check the summary component http://192.168.0.2:6006/?path=/story/summary--default
=> fixed formatting of the TextArea in the Summary

__mocks__/use-resize-observer.ts, components/Cases/CaseRecap/__snapshots__/CaseRecap.spec.jsx.snap, components/ShowMoreBox/ShowMoreBox.module.scss, components/ShowMoreBox/ShowMoreBox.spec.tsx, components/ShowMoreBox/ShowMoreBox.tsx, components/ShowMoreBox/__snapshots__/ShowMoreBox.spec.tsx.snap, components/Summary/Summary.stories.jsx, components/Summary/SummaryList.tsx, components/Summary/__snapshots__/SummaryList.spec.tsx.snap, components/WarningNote/WarningNoteRecap/__snapshots__/WarningNoteRecap.spec.tsx.snap, package.json, yarn.lock
**What**  
Added "show more" for textAreas longer than 3 lines.
The check of the element height is done using `ResizeObserver`
- spin up storybook
- check http://192.168.0.2:6006/?path=/story/summary--default
- check that everything looks good
=> Added show more for long textAreas in Summary list

components/Steps/ReviewWarningNoteConfirmation.spec.tsx, components/Steps/ReviewWarningNoteConfirmation.tsx, components/Steps/__snapshots__/ReviewWarningNoteConfirmation.spec.tsx.snap, data/forms/warning-note-review.tsx, pages/people/[id]/warning-notes/[warningNoteId]/[[...stepId]].tsx, pages/people/[id]/warning-notes/[warningNoteId]/index.tsx
**What**  
Add the review form to the warning note review/end page, add custom confirmation component to display the correct messages once a warning note has been reviewed or ended
**Why**  
This form allows users to review a warning note and update its details or if need be end the warning note
The backend implementation is still not implemented as such this PR is only for getting the form ready once the backend  is ready.
=> Review warning note form

components/WarningNote/WarningNotes.tsx, components/WarningNote/__snapshots__/WarningNotes.spec.tsx.snap, data/forms/warning-note-review.tsx, pages/people/[id]/warning-notes/[warningNoteId]/[[...stepId]].tsx
**What**  
The dates displayed on the warning note component on the person details page now uses the correct dates. This being the start date becoming the review date once a note has been reviewed and the review date section to display the next review date. 
The showConditionalGuides property has been added to the renew date on the warning note review form.
=> Change warning note start date to display reviewed date and add missing showConditionalGuides to review form

data/forms/warning-note.tsx
**What**  
Show a custom warning types list for childreny
- check __adults__ http://dev.hackney.gov.uk:3000/people/234/warning-notes/add
- check __children__ http://dev.hackney.gov.uk:3000/people/321569/warning-notes/add
- they should show different lists
=> fixed warning types for children

data/forms/warning-note-review.tsx, data/forms/warning-note.tsx
**What**  
Added missing validation for `warning-note-review` form and missing hint for `warning-note` form
- go to http://dev.hackney.gov.uk:3000/people/44000000/warning-notes/123
- check that the review date is working properly
=> added validation for review date

components/Form/DateInput/DateInput.tsx
**What**  
Trigger date input `onchange` only if the input is valid
The problem was that the component is returning the date as string `yyyy-mm-dd` if month was `-1` it was like `yyyy--1` and because of that was setting the day as `1` that is invalid as it should be 2 digits and the error was there until you changed the day input.
**Steps to reproduce the bug**
- go https://social-care-service-staging.hackney.gov.uk/people/234/warning-notes/add
- enter `12 12 2000` as first date
- press enter to submit the uncompleted form
- change the month to `-`1
- press enter
- change the month to `12`
- the error is still there
=> fix date input when month is a negative value

components/FormWizard/FormWizard.jsx, components/PersonView/PersonView.tsx, data/forms/create-new-person.tsx, pages/people/[id]/index.tsx, pages/people/[id]/update/[[...stepId]].tsx, pages/people/add/[[...stepId]].tsx, stylesheets/all.scss, utils/api/residents.ts
**What**  
- created `/people/:peopleId/update` page
- extended `PersonView` with `canEdit` flag
- made `stepHeader` configurable in the `FormWizard`
- the _update person_ is going to visible only for admins
**What is missing**
- the endpoint integration, waiting for the BE
- go to person people view
- click "update person"
- check the form is autofilling (note: some mapping has to be done by the BE)
=> Update new person

components/Form/PhoneInput/PhoneInput.tsx
**What**  
This is needed to support "re-population" of the input on _edit person_.
At the moment the data is not in a good shape and often there is text inside the number field.
=> Extend phone numbers to support text

package.json, yarn.lock
**Why**  
Storybook wasn't compiling with `sass-loader@11`.
Storybook should work now :)
=> downgrade sass-loader to make storybook happy

components/AddForm/AddForm.tsx, components/AddForm/__snapshots__/AddForm.spec.tsx.snap, components/WarningNote/WarningNotes.tsx, data/forms/warning-note-review.tsx, data/forms/warning-note.tsx, factories/warningNotes.ts, pages/api/residents/[id]/warningnotes/index.ts, types.ts
**What**  
- aligned warning notes `POST` object to BE
- fixed API `/residents/:id/warningnotes` (now the BE is returning `200` even if there aren't notes)
- added warningnote to the forms (only for admins)
- go into a person page
- click add record
- search for **warning note**
- add a warning note
- check that it appears correctly in the person page
=> aligned warning notes BE names

components/Form/Checkbox/Checkbox.tsx, components/Form/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
**What**  
Only if `options` is present it wraps the `checkbox` with a `fieldset`.
**Why**  
It solves an accessibility proble.
=> use fieldset only if there options

lib/cases.spec.ts, lib/cases.ts
**What**  
The current regex was breaking in case JSON was containing `(${text}), `.
Now the RegEx has been fixed.
Ideally the BE should filter out this property but it's a quick fix in the meantime.
=> fixed cases sanitisation regex

components/Cases/Cases.spec.tsx, components/Cases/Cases.tsx, lib/residents.spec.ts, lib/residents.ts, pages/people/[id]/edit/[[...stepId]].tsx, types.ts
**What**  
- Fixed `restricted` on resident object, aligned it to the BE API
- Fixed re-population of the "restricted" input on resident edit
- Check an edit resident page
- The "restricted" input is re-populated as expected
=> fixed restricted on resident

data/forms/warning-note-review.tsx, lib/warningNotes.spec.ts, lib/warningNotes.ts, pages/api/warningnotes/[warningNoteId].ts, pages/people/[id]/warning-notes/[warningNoteId]/[[...stepId]].tsx, utils/api/warningNotes.ts
**What**  
This PR adds the PATCH endpoint call to the front end with all the required data.
**Why**  
To allow users to add a review to a warning note and either end it or renew it.
Would like some feedback on some of my decisions here specially on the tests for the API call and how I get the `endedDate` property.
The table with information won't render as of yet as the GET endpoint for an individual note doesn't seem to be ready, furthermore in a future PR the note must not be allowed to be re-reviewed if it is ended.
=> Wire up PATCH warning note endpoint to front end

components/Steps/PersonLinkConfirmation.spec.tsx, components/Steps/PersonLinkConfirmation.tsx, components/Steps/__snapshots__/PersonLinkConfirmation.spec.tsx.snap, pages/people/[id]/records/case-notes-recording/[[...stepId]].tsx, pages/people/[id]/warning-notes/add/[[...stepId]].tsx
**What**  
- refactored `DetailsConfirmation` into `PersonLinkConfirmation`
- used `PersonLinkConfirmation` to the add warning note
- added `back to search` and `view person` buttons to _add warning notes_ and _case notes recording_
=> Fixed add warning note confirmation

pages/people/[id]/index.tsx
**What**  
Editing permission for `edit person`, functionality is currently only being deployed for children's workers.
**Why**  
Based on what different organisations are requesting permission for.
=> update permissions - childrens can edit person not adults

components/AddForm/AddForm.tsx, components/Cases/CaseLink.tsx, components/Cases/CaseRecap/CaseNote.tsx, data/forms/asc-conversation-3.tsx, data/forms/index.tsx, data/googleForms/adultForms.ts, pages/people/[id]/records/conversation-3/[[...stepId]].tsx
this pr activates our first iteration of the conversation 3 form, making it available and ready for use by practitioners.
it:
- launches our conversation 3 form rather than the google form when adding a new record
- updates `/pages/person/[id]/records/conversation-3` form to submit answers as a new record
- modifies the `CaseNote` component to support displaying answers from the conversation 3 form
- makes some lightweight usability improvements to the conversation 3 form, like adding missing error messages
we know that there are issues with the ux of this form and the wording of questions. we're intending to iterate on this quickly, but it's important to launch this as-is to solve a pressing need for practitioners.
=> activate the first version of conversation 3

components/Cases/CaseLink.tsx
The creation of a warning note is visible in record history, but the ‘view’ link is missing. 
This is live in production, so this is a quick PR to try and fix this. 🤞🏾
=> Quick Fix: Add view link for a warning note

components/Cases/CaseLink.tsx, types.ts
**What**  
The creation of a warning note is visible in record history, but the ‘view’ link is missing.
This adds a condition to the case link component to render a `view` link to the warning note
within the records history.
It also adds a warning note id attribute to the case form data type so that it can be used to create the relevant path.
=> Add view link to a created warning note in the records history

.gitignore
**What**  
If you run `yarn storybook-build` it generates a `./storybook-static` dir that we wouldn't want to commit to git. This adds that dir to our `.gitignore`
=> chore: add storybook-static dir to gitignore

components/Layout/Header/Header.spec.tsx, components/Layout/Header/Header.tsx, components/Layout/Header/__snapshots__/Header.spec.tsx.snap, pages/login.tsx
our language and design patterns for signing in and out are now [consistent with the hackney design system](https://design-system.hackney.gov.uk/patterns/sign-in).
specifically, we use "sign in/out" language rather than "log in/out", and have improved the microcopy on the sign in page.
we've left the paths of these pages unmodified to avoid accidentally creating bugs.
=> compy with hackney sign in patterns

pages/404.tsx
it adds a [proper branded 404 page](https://www.netlify.com/blog/2020/12/08/making-a-custom-404-page-in-next.js/) that is consistent with [design system guidance](https://design-system.service.gov.uk/patterns/page-not-found-pages/)
=> add a 404 page

serverless.yml
**What**  
Increase Lambda timeout to 30s
**Why**  
This will improve the situation where the Lambda times out due to backend performance issues
This is a temporary change to help us further diagnose the performance issues. Once we have improved the situation at the backend this need to be reverted back to 10s.
=> (SCT-213) increase Lambde timeout to 30s

components/PersonView/PersonView.spec.tsx, lib/permissions.spec.ts, lib/permissions.ts
**What**  
ASC have signed off the "Edit person" functionality, so this activates it for those residents.
~Note: currently in draft while we assess when this will go live – it'll also need some tweaks once https://github.com/LBHackney-IT/lbh-social-care-frontend/pull/362 goes in~ Done in https://github.com/LBHackney-IT/lbh-social-care-frontend/pull/365/commits/1c3c162d3bfd705179a8c00e00e2cbf83b9cd85d
- ~Have you added any new third-party libraries?~
- ~Are any new environment variables or configuration values needed?~
- ~Anything else in this PR that isn't covered by the what/why?~
=> feat: Activate edit person functionality for ASC residents

pages/people/[id]/index.tsx
[Ticket](https://hackney.atlassian.net/browse/SCT-204)
**What**  
Adding dev-only view parameter for relationships.
canViewWarningNotes function has been renamed to canViewArea so it applies also to Relationship (other than warning notes)
The function itself evaluates only the user.hasDevPermissions, so it applies in this case to both
**Why**  
To make the section visible to developers only in staging
=> SCT-204 - Write front end views for displaying relationships

pages/workers/[id]/edit/[[...stepId]].tsx
**What**  
Added a null condition accessor for getting the name property of teams[0] as teams can be an empty array.
**Why**  
When loading the edit worker page you get logged out.
- Have you added any new third-party libraries? no
- Are any new environment variables or configuration values needed? no
- Anything else in this PR that isn't covered by the what/why? no
=> fix(SCT-261): Allow edit worker page to load if teams is an empty array

components/Form/DatePicker/DatePicker.spec.tsx, components/Form/DatePicker/DatePicker.tsx, components/Form/types.ts, data/forms/asc-case-notes-recording.tsx, data/forms/cfs-case-notes-recording.tsx
this makes it easier/faster to add a case note to a person by:
- using `<input type="date"/>` rather than the more complicated "three text inputs" style
- enhances the `<DatePicker/>` element with a prop that causes it to render with today's date as an intial value
- reconfigure the form configuration data to use that prop for the case note form
=> feature(SCT-248): Todays date by default for case notes

components/WarningNote/WarningNoteRecap/WarningNoteRecap.tsx, cypress/integration/view_warning_note_details.ts, pages/people/[id]/warning-notes/[warningNoteId]/view/[[...stepId]].tsx, types.ts
**N.B:** See this [user story](https://hackney.atlassian.net/browse/SCS-510) for a more detailed user journey for ending a warning note.
**What**  
This adds a page to view warning note reviews from the records history section. i.e when the user clicks `view` next to a **Warning Note Ended** record:
**Before:**
Clicking the view link would take the user to a page that only showed the details of the initial warning note and did not display any review information:
**After:**
Now, clicking the view link would take the user to a page displaying all the reviews submitted up until the warning note was closed as well as the original warning note itself:
**Why**  
When a warning note is ended, a log of this action is made in the records' history section. The view link takes the user to a warning …
=> feat(SCT-229): Create warning note end details page

components/FlexibleForms/StepForm.tsx
in the source codebase, warning the user about unsaved changes was linked with autosave functionality.
since we've gutted autosave for now, we're no longer warned about unsaved changes.
this fixes that by using formik's `dirty` feature. when we bring autosave back we will revisit this.
=> warn about unsaved changes, interim fix

components/Dashboard/DashboardWrapper.tsx, components/Dashboard/__snapshots__/DashboardWrapper.spec.tsx.snap, pages/__dashboard.tsx, pages/index.tsx
**What**  
We want to test the dashboard with some stakeholders before launching it for all customers. This PR makes an obfuscated URL `{domain}/__dashboard` which allows us to navigate to it, and demo the behaviour, without exposing it in navigational elements, or showing it to all users on the home page.
The ticket to undo this change / launch the dashboard is [SCT-401](https://hackney.atlassian.net/browse/SCT-401).
**Why**  
[SCT-400](https://hackney.atlassian.net/browse/SCT-400)
- ~Have you added any new third-party libraries?~
- ~Are any new environment variables or configuration values needed?~
- ~Anything else in this PR that isn't covered by the what/why?~
=> feat(SCT-400): expose dashboard at a hidden URL for testing

components/Form/DateInput/DateInput.tsx, components/Form/FieldErrorMessage/FieldErrorMessage.spec.tsx, components/Form/FieldErrorMessage/FieldErrorMessage.tsx, components/Form/Radios/Radios.tsx, components/Form/TextArea/TextArea.tsx, components/Form/TextInput/TextInput.tsx, components/Form/types.ts, data/forms/warning-note-review.tsx
**What**  
Adds 'required' error messages to form fields that are required. This is done through a new `<FieldErrorMessage />` component that automatically crafts an appropriate error message if `error.type`  is `required` but `error.message` is empty.
The error message automatically switches from `a` to `an` depending on whether label starts with a vowel, and formats in sentence case.
Note: Further refinement may be needed if there are specific field names that need more advanced error messages, but this can still be done in the form config by passing a string to the `required` value.
**Why**  
[SCT-355](https://hackney.atlassian.net/browse/SCT-355), [SCT-366](https://hackney.atlassian.net/browse/SCT-366)
- ~Have you added any new third-party libraries?~
- ~Are any new …
=> feat(SCT-355, SCT-366): add required validation error message to Warning Notes form fields

data/forms/warning-note-review.tsx, types.ts
**What**  
We've made a change in the structure of the API response when we request warning note reviews, so this reverses the previous change made in the frontend.
**Why**  
This was initially changed because the `reviewNotes` did not match the property
in the API response when we make a GET request for warning note reviews. 
See changes made in this [PR](https://github.com/LBHackney-IT/lbh-social-care-frontend/pull/391) for better context.
The API response was returning a `Notes` property for each warning note review object.
From discussing the current naming conventions for the warning note data model,
it was agreed that any details of a review should be saved as `review notes`
and `notes` should be reserved for the original warning note.
=> Undo change to reviewNotes component in review form step

data/forms/warning-note-review.tsx, data/forms/warning-note.tsx
**What**  
When filling a form to either create or review a warning note or end a warning note, 
some date inputs were missing specific validation on them and did not display an error on the form when invalid e.g
**Before**
**Why**  
It was found from testing creating/reviewing a  warning note that the following date types were missing validation on the frontend and did not prevent the user from inputting an invalid value.
Date Type | Validation Required
-- | --
manager discussion date | Can not be a future date
start date | Can not be a future date
end/review date | It cannot be over a year since the start date
‘next review date’ (a conditional field that appears when renewing warning note) | It cannot be more than 1 year from the date review was undertaken.
**After**
=> Fix(SCT-461): Add missing date validation when creating/reviewing a warning note

components/FormWizard/FormWizard.jsx
When we click on `save and finish later` we are redirected to a page not found. URL path: `/form-in-progress`.
We checked the URL of the forms to complete tab in the dashboard and realised that the path for the forms tab was: `/forms-in-progress`
This corrects the path when clicking the save and finish later buttonto redirect the user to the dashboard forms to the complete tab.
=> Fix(SCT-492): Add missing "s" in URL path when saving a form

data/forms/warning-note.tsx
A follow up to this PR #443.
This adds a check to prevent a user from setting a `Date Informed` value for the future.
=> Fix(SCT-461): Add missing date validation for Date Informed form component

components/Search/results/ResidentsTable.spec.tsx, components/Search/results/ResidentsTable.tsx, components/Search/results/__snapshots__/ResidentsTable.spec.tsx.snap, types.ts
**What**  
Some resident's have partial addresses (e.g. missing postcode). Our UI doesn't gracefully handle these situations, until now!
**Why**  
[SCT-509](https://hackney.atlassian.net/browse/SCT-509)
=> fix(SCT-509): safely handle residents with partial addresses

components/Form/DateInput/DateInput.tsx
[Link to the ticket](https://hackney.atlassian.net/browse/SCT-491)
**What**  
Internal fields (day/month/year) "onChange" validation has been removed. 
The internal validation was preventing the fields to be set to empty, as it was being triggered by the onChange function.
Validation now is at the ControlledDateInput component level, where it checks if the date is valid (or null)
**Why**  
Fixed the date input component so dates can be set to null.
=> SCT-491 - Date of death, once set, can't be removed

components/WarningNote/WarningNoteRecap/WarningNoteRecap.tsx, cypress/integration/view_warning_note_details.ts, data/forms/warning-note-review.tsx, pages/people/[id]/warning-notes/[warningNoteId]/[[...stepId]].tsx
**What**  
The form for submitting an adult warning note review was not displaying a radio option component that would ask the user if they have discussed the warning note review with the individual.
_**Before**_
_**After**_
**Why**  
The changes made include separating the `formSteps` used for generating the warning note review form into two:
- reviewFormStepsAdult
- reviewFormStepsChild
Previously, we used the `conditionalRender` parameter to display the `disclosure question` component depending on whether the person was an adult or child. However, this `conditionalRender` required the person object to be passed into the relevant formsStep component, and it did not seem to be picking up the person object. 
(Attempted to pass the person object in as part of the `formSteps` but couldn't …
=> Fix(SCT-507): Update ASC warning note review form to include a disclosure question

components/Search/results/ResidentsTable.tsx, components/Search/results/__snapshots__/ResidentsTable.spec.tsx.snap
**What**  
Since the new search UI went live with the dashboard, the `RESTRICTED` label has looked a little off! This removes address, and expands the header to cover the label.
**Why**  
[SCT-505](https://hackney.atlassian.net/browse/SCT-505)
=> fix(SCT-505): fix placement of the RESTRICTED label with new search UI

components/AllocatedCases/MyAllocatedCases.spec.tsx, components/AllocatedCases/__snapshots__/MyAllocatedCases.spec.tsx.snap, components/Cases/CaseRecap/__snapshots__/HistoricVisit.spec.tsx.snap, components/Dashboard/__snapshots__/DashboardWrapper.spec.tsx.snap, components/ErrorMessage/ErrorMessage.tsx, components/ErrorMessage/__snapshots__/ErrorMessage.spec.tsx.snap, components/Form/FieldErrorMessage/FieldErrorMessage.spec.tsx, components/Search/Search.spec.jsx, components/WorkerView/__snapshots__/WorkerSearch.spec.tsx.snap
this professionalises our default error message
from the [gov uk design system](https://design-system.service.gov.uk/components/error-message/):
> Do not use humourous, informal language like ‘oops’
=> use a more appropriate default error message

components/DuplicateWarningPanel/DuplicateWarningPanel.module.scss, components/DuplicateWarningPanel/DuplicateWarningPanel.spec.tsx, components/DuplicateWarningPanel/DuplicateWarningPanel.tsx, components/Search/Search.jsx, components/Steps/Summary.tsx, pages/people/add/[[...stepId]].tsx, utils/urls.ts
this builds on https://github.com/LBHackney-IT/lbh-social-care-frontend/pull/444 by adding an extra "speedbump" to the add new person flow, which warns the user about potential duplicates before they hit the confirm button.
we hope this will result in fewer duplicate people being created.
it does this by:
- adding a new `DuplicateWarningPanel` component which is fed the data that the user typed about the new person they'd like to add
- the component is rendered on the "review details" step of the add new person flow
- the component searches for potential matches with the same surname and first name as the new one, if it finds none, it renders nothing. otherwise, the user sees a prompt with a table of possible duplicates
we want to improve on this further by making enhancements to the …
=> Improve add person flow

components/ConfirmationBanner/ConfirmationBanner.module.scss, components/ConfirmationBanner/ConfirmationBanner.spec.tsx, components/ConfirmationBanner/ConfirmationBanner.stories.tsx, components/ConfirmationBanner/ConfirmationBanner.tsx, components/Icons/TickCircle.tsx
> suggestion for a new design pattern
> rather than the big chunky confirmation messages intended for resident-facing services, which take up a whole page, we're going to use something like this for the end of a submission on #sct-assessing-and-recording
> probably we should be consistent and use it elsewhere too.
> it would appear at the top of a page, and in our situation it would be the person page that a user is returned to
https://hackit-lbh.slack.com/archives/C022164F8GN/p1623666838005100
the component is basically a re-skinned `lbh-panel`, but with an extra `alert` aria role to suit the fact that is no longer the central protagonist of a page
this will be used for the new form builder/submissions engine we're building, but could also be used for situations like:
- creating a person …
=> add confirmation banner component

components/AllocatedWorkers/AllocatedWorkers.tsx, cypress/integration/allocate_worker.ts, lib/permissions.spec.ts, lib/permissions.ts, pages/people/[id]/allocations/add.tsx
**What**  
It has been raised that we were having some issues with allocating workers. As part of my investigation it seemed we didn't have many (if any) automation tests around the behaviour, especially the permissions. 
This PR:
* Refactors the logic used for rendering the allocation form to use the same permission function as rendering the "Allocate worker" button
* Adds Cypress tests for the button and add allocation form
* Adds unit tests for the updated permission method
**Why**  
To give us confidence the system works, which it does, this is just a refactor!
=> feat: improve testing for worker allocation behaviour

pages/api/submissions/[id]/index.ts, pages/api/submissions/[id]/steps/[stepId].tsx
might result in a miniscule performance improvement too, because we only now fetch `user` when we need it
=> make submission api route code more readable

components/Search/Search.jsx, cypress/integration/search_for_person.ts
**What**  
Added  check for data != 1 (useSWRinfinite)
**Why**  
When searching for residents, and using the "Clear search" mechanism, the app redirects to the login page due to an error
This is not the definitive solution, but it will prevents the app from breaking when the user search twice
=> SCT-511 - App redirects to login when "Clear search" is used

pages/_document.tsx
[Link to ticket](https://hackney.atlassian.net/browse/SCT-614)
**What**  
Added HotJar code in Head tag (available in every page in production-only environment)
**Why**  
This enables HotJar analytics for the application
Code has been added in the same fashion as googletagmanager and google analytics
=> SCT-614: Added HotJar code in Head tag

lib/relationships.spec.ts, lib/relationships.ts
**What**  
Changed the Relationship call in the frontend to use the v1 endpoint
**Why**  
To keep functionality working while we work on the relationship
=> SCT-590 - Moved API endpoint to V1

components/pages/warning-notes/AddWarningNoteForm/AddWarningNoteForm.spec.tsx, components/pages/warning-notes/AddWarningNoteForm/__snapshots__/AddWarningNoteForm.spec.tsx.snap, data/forms/warning-note-review.tsx, data/forms/warning-note.tsx
**What**  
Make the `Manager's Name` and `Discussed With Manager` fields optional for ASC warning notes.
**Before: (Both fields required on a ASC warning note form)**
**After: (Both now optional)**
**Why**  
Request from a stakeholder review was that the two manager fields on an ASC warning note be set to optional.
Test in staging
=> Fix(SCT-617): Set manager fields to optional

pages/submissions/[id]/index.tsx, pages/submissions/[id]/steps/[stepId].tsx
Co-authored-by: Ana Bebic <anabebs@users.noreply.github.com>
**What**  
create redirect on the answers page of a submission so that a user is not able to edit already submitted forms.
=> redirect to finished submission on completion

components/PersonWidget/PersonWidget.spec.tsx, components/PersonWidget/PersonWidget.tsx, components/PersonWidget/__snapshots__/PersonWidget.spec.tsx.snap, factories/residents.ts, lib/residents.spec.ts
**What**  
small PR to update the person widget so that it uses both address and addresses when required.
This will fix the problem of the address not displaying on the form answers page.
=> add address display to form answers page

components/Cases/CaseLink.spec.tsx, components/Cases/CaseLink.tsx, components/Cases/Cases.spec.tsx, components/Cases/Cases.tsx, components/Cases/CasesTable.tsx, components/Cases/__snapshots__/CaseLink.spec.tsx.snap, components/Cases/__snapshots__/Cases.spec.tsx.snap, components/Cases/__snapshots__/CasesTable.spec.tsx.snap, components/Search/Search.spec.jsx
modify the records table code to show submissions made with the new flexible form builder.
essentially, it works by grabbing the `recordName`, checks whether it matches the id of any of the configured flexible forms, and if so, treats it as a flexible form submission.
if not, the existing logic applies.
it also makes some minor tweaks to use sentence case.
=> show submissions in records table

components/FlexibleForms/CheckboxField.tsx, components/FlexibleForms/ComboboxField.tsx, components/FlexibleForms/RadioField.tsx, components/FlexibleForms/RepeaterField.tsx, components/FlexibleForms/SelectField.tsx, components/FlexibleForms/StepForm.spec.tsx, components/FlexibleForms/TextField.tsx, data/flexibleForms/review3C.ts
**What**  
This PR adds the required fields on the review 3c form, Each flexible form component now also displays a red asterisk if the field is required
**Why**  
To allow the review 3c form on the system to contain the correct required fields like on the google form.
=> Sct 625 3c required questions

components/AddForm/AddForm.tsx, data/googleForms/adultForms.ts
this launches the new flexible form builder by making the new review 3c form accessible from `dev.hackney.gov.uk:3000/people/1/records`, effectively removing the feature flag for the feature.
out first few forms will be adults, so we check for an adults `ageContext` before showing the new options.
when we branch out into children's forms too, we should refactor the way this works, likely by adding an availability key to each form's config indicating who it should be available to
=> launch the new review 3c form!

components/Relationships/RelationshipElement.spec.tsx, components/Relationships/RelationshipElement.tsx, factories/relationships.ts
**What**  
Reversed the ordering in the frontend for Relationships
**Why**  
The order was alphabetical but reversed
=> SCT-414 - reversed ordering

.circleci/config.yml, .release-it.json
**What**  
We have to set the GitHub username and email when we run `git commit` inside the CircleCI context
=> fix(SCT-724): set the GitHub username and email

components/Search/MainSearchWrapper.tsx, components/Search/Search.jsx, components/Search/Search.spec.jsx, components/Search/__snapshots__/MainSearchWrapper.spec.tsx.snap, pages/my-records.tsx
**What**  
This PR updates the content at the top of the Search page.
Before | After
-- | --
**Why**
To provide better clarity around the difference between "Search for a person" and "Search for a record".
**Link to Jira ticket**
https://hackney.atlassian.net/browse/SCT-628
=> feat(SCT-628): update descriptions of search features on Search page

.circleci/config.yml, ci-scripts/delete-draft-github-releases.js, ci-scripts/delete-draft-github-releases.spec.js, package.json, yarn.lock
**What**  
When we create draft releases with `release-it`, instead of extending the previous draft, it creates a new one, meaning we end up with a deluge of draft releases!
I've written a small script which clears up old draft releases automatically, meaning the one `release-it` creates is always fresh, and contains all changes since the last production releases. 
This draft is then removed and replaced when a full production release is made.
=> fix: clear out old draft releases before creating a new one

.circleci/config.yml
**What**  
For CircleCI to be able to push back to GitHub, we need to give it a write-access deploy key. This has been set up in CircleCI, and this is the relevant config for it.
Assuming this works (I have a feeling we're going to hit another issue with push rights to `main`), then I will add some documentation to the `README` on how these keys are configured, should we need to change it in the future.
Relevant docs: https://circleci.com/docs/2.0/gh-bb-integration/#creating-a-github-deploy-key
=> fix: allow CircleCI to push to GitHub

lib/submissions.spec.ts, lib/submissions.ts
**What**  
This PR changes the `createdBy` property within the body of the finished submission endpoint to align with the back end API, the submission state has also been added
**Why**  
To align the front-end for case submissions to the back-end
=> SCT-729 Sync submissions with back end

components/pages/warning-notes/ReviewWarningNoteForm/ReviewWarningNoteForm.tsx, lib/warningNotes.spec.ts
We don't need to grab the time from the client machine and pass it as an `endedDate` value from the frontend when a warning note is closed.
The end date is saved to a closed warning note automatically within the backend.
This removes the `endedDate` parameter from the `formData` passed to the `updateWarningNote` method.
=> chore(SCT-727): Remove ended date parameter from PATCH warning note request body

components/WarningNote/WarningNotes.spec.tsx, components/WarningNote/WarningNotes.tsx, components/WarningNote/__snapshots__/WarningNotes.spec.tsx.snap, components/pages/people/PersonDetailsPage.spec.tsx, components/pages/people/PersonDetailsPage.tsx, components/pages/people/__snapshots__/PersonDetailsPage.spec.tsx.snap
**What**  
We did a fix to ensure practitioners could see warning notes for their residents last week. This extends that change to show warning notes for all users (but only users with the right permissions can `review / end` them).
**Why**  
[SCT-661](https://hackney.atlassian.net/browse/SCT-661)
=> fix(SCT-661): display warning notes for all users

.circleci/config.yml, package.json
**What**  
At the moment our pipeline builds the app three times:
1. To run end-to-end tests
2. To deploy to staging
3. (Optionally) To deploy to production
The downside here is that _technically_ the artefact used for running our tests is not the same artefact we release to staging and production. This introduces a small opportunity for bugs to be introduced. To eliminate this, and also speed up the whole process, I have split out the build step as an independent job that runs just once, after the unit tests have passed.
_Draft while I do some testing in CI_
=> fix: only build the app once in CI

.github/CONTRIBUTING.md, jest.config.js, lib/feature-flags/feature-flags.spec.tsx, lib/feature-flags/feature-flags.tsx, package.json, yarn.lock
**What**  
Following the introduction of `<ConditionalFeature />`, this PR introduces a new hook for accessing the state of a feature flag during scripting (outside of the JSX rendering tree), for example, inside a `useEffect`.
**Why**  
[SCT-738](https://hackney.atlassian.net/browse/SCT-738)
- Yes – [`@testing-library/react-hooks`](https://github.com/testing-library/react-hooks-testing-library)
- ~Are any new environment variables or configuration values needed?~
- ~Anything else in this PR that isn't covered by the what/why?~
=> feat(SCT-738): add a `useFeatureFlag()` hook for accessing feature flags

components/Search/MainSearchWrapper.tsx, components/Search/__snapshots__/MainSearchWrapper.spec.tsx.snap
**What**  
Update the tab "Search for records by person" to "Search for records".
**Why**  
In https://github.com/LBHackney-IT/lbh-social-care-frontend/pull/505, we updated the descriptions for the search features but we missed out a very smol content change that was supposed to be a part of request design changes.
**Link to Jira ticket**
https://hackney.atlassian.net/browse/SCT-628
=> style(SCT-628): update search for records tab name to "Search for records"

components/FlexibleForms/TagsField.tsx
**What**  
Error was being thrown because sometimes `tags` is undefined so calling .map errors out. Just a minor check to confirm tags is defined first.
=> fix: Don't throw error on empty tags

components/AddForm/AddForm.spec.tsx, data/flexibleForms/sgAdultManagerDecisionConcern.ts
**What**  
This PR makes the safeguarding adult manager concern form not viewable on production.
**Why**  
To test the form on staging first before allowing practitioners access on production
=> make adult manager form not be viewable on production

components/AddForm/AddForm.spec.tsx, data/flexibleForms/faceOverview.ts
**What**  
One line change to make sure the face overview form can only be seen by dev/admin users and not currently adult workers.
**Why**  
Not been signed off yet!
=> bug: remove adults permission to see face overview form

components/AddForm/AddForm.spec.tsx, data/flexibleForms/faceOverview.ts, data/flexibleForms/sgAdultConcern.ts
**What**  
Tiny change to make safeguarding adult concerns form only viewable by admin or dev users. Hidden from adult social workers.
**Why**  
Waiting on comms for release.
=> bug(): Safeguarding adult concerns should only be seen by admins

serverless.yml
**What**  
This PR adds the three required gov notify environment variables to the serverless configuration. These variables exist on staging and will be added to production once it is confirmed to work.
**Why**  
To allow the approval functionality to utilise gov notify to send emails
three environment variables have been added to the staging environment: `notify-api-key`, `notify-approver-template-id` and `notify-return-for-edits-template-id`
=> feature(SCT-808): Add gov notify variables to serverless

components/RevisionTimeline/MiniRevisionTimeline.module.scss, components/RevisionTimeline/RevisionTimeline.spec.tsx, components/RevisionTimeline/RevisionTimeline.tsx, factories/submissions.ts
**What**  
This PR adds when a form has been approved to the submission's history timeline
**Why**  
To allow managers and workers to see when a submission has been approved, at what time and by who
=> Feature: Approval on submission history timeline

components/pages/people/relationships/add/AddRelationshipForm.spec.tsx, components/pages/people/relationships/add/AddRelationshipForm.tsx, data/forms/add-relationship.tsx
**What**  
Update add relationship form to show select person name.
Before | After
--|--
**Why**  
So the practitioners don't have to remember the person they've selected to add the relationship with.
=> feat(SCT-471): update add relationship form to show select person name

components/pages/people/relationships/view/Relationships.spec.tsx, components/pages/people/relationships/view/Relationships.tsx, factories/relationships.ts, types.ts
**What**  
Add if a related person is a main carer and display their gender and any details added to the relationship.
Before | After
--|--
**Why**  
We need to display what we have as fields in the add relationship form.
=> feat(SCT-471): add main carer, gender and details to view relationships

components/AddForm/AddForm.spec.tsx, data/flexibleForms/review3C.ts
**What**  
Stop displaying option for review 3c form
**Why**  
Asked to by the service
=> fix: Stop sharing review 3c flexible form with adult social care workers

components/pages/people/relationships/view/Relationships.tsx
**What**  
Fixed the "add a new relationship" button link so it works again
**Why**  
After the page redesign, the link was not working anymore
=> Fix for "add relationship" link after page design change

components/AllocatedWorkers/AllocatedWorkers.tsx
**What**  
Fix for the "Allocate worker" button link
**Why**  
After the page redesign, the link doesn't work anymore
=> Fix for "Allocate worker" button link

components/pages/people/relationships/remove/RemoveRelationshipDialog.module.scss, components/pages/people/relationships/remove/RemoveRelationshipDialog.spec.tsx, components/pages/people/relationships/remove/RemoveRelationshipDialog.tsx, components/pages/people/relationships/view/Relationships.spec.tsx, components/pages/people/relationships/view/Relationships.tsx, features.ts, lib/relationships.spec.ts, lib/relationships.ts, pages/api/relationships/[id].ts, pages/people/[id]/relationships.tsx, utils/api/relationships.spec.ts, utils/api/relationships.ts
**What**  
Add `Remove` link for each relationship that opens up a dialog to confirm removal. The endpoint currently points to our SwaggerHub endpoint and is **under a feature flag** which means it's only visible on local dev and staging.
https://user-images.githubusercontent.com/42817036/125938635-7d8b701f-9bc0-411a-9ecb-688d7287bd8b.mov
**Why**  
We want to allow users to be able to remove a relationship.
Some follow-up actions include adding a Cypress test that will add and remove a relationship, refactoring some tests and eventually point to the real service API endpoint.
=> feat(SCT-481): create flow for removal of a personal relationship

.circleci/config.yml, next.config.js
**What**  
Disables OWASP baseline scan as the content security policy is too restrictive and blocks google fonts and tag manger.
Disabling is a temporary fix to free the cd pipeline. Work to follow with a correct CSP will re-enable
=> fix(SCT-545) Disable owasp scan

components/AddFormDialog/AddFormDialog.spec.tsx, components/AddFormDialog/AddFormDialog.tsx, data/flexibleForms/childCaseNote.ts, data/flexibleForms/forms.types.ts
in the `<AddFormDialog/>`, support weird forms (case notes, warning notes) that have their own special routes and aren't at the normal `/submissions/new...` path
=> add canonical urls to forms

pages/api/submissions/[id]/index.ts
**What**  
Seems some hardcoded form answers for finishing a submission was left in by mistake!
**Why**  
Because it's a bug, definitely shouldn't be left in
=> fix: Remove weird hardcoded form answers

pages/people/[id]/case-note.tsx
fix a tiny edge case where if you click the submit button while the form is invalid, the form would inadvertently set `finished` to true
=> fix: case note submit bug

components/AddFormDialog/AddFormDialog.spec.tsx, components/AddFormDialog/AddFormDialog.tsx
make it easier for admins and people with elevated permissions to understand which forms are shown specially and which are normally seen, by adding an "In preview" message to some.
=> feat: mark preview forms

data/flexibleForms/childCaseNote.ts
**What**  
Make the CFS case note form not yet viewable as not approved!
**Why**  
Because the form requires approval to be released.
- Have you added any new third-party libraries? no
- Are any new environment variables or configuration values needed? no
- Anything else in this PR that isn't covered by the what/why? no
=> fix: hide cfs case note form

data/flexibleForms/childCaseNote.ts, data/googleForms/childForms.ts
**What**  
Make sure we show the original google forms for CFS case notes
**Why**  
practitioners require these forms
=> Fix: Bring back cfs case note google forms

components/pages/people/relationships/view/Relationships.tsx, utils/api/relationships.spec.ts, utils/api/relationships.ts
**What**  
- Add headings to relationships table.
- Fix bug where if you selected a relationship type with a single checkbox option e.g. Aunt / uncle, friend and selected main carer, it didn't send it as part of the request so main carer never showed up when you went to view the relationship
Before | After
--|--
**Why**  
This was part of feedback received about relationships.
=> feat(SCT-471): add headings to relationships table

components/NewPersonView/Event.tsx, components/NewPersonView/PersonTimeline.tsx
the timeline synthesises/integrates many different random date formats. to display these in a standard way, we first need to normalise them to an iso-compatible format.
it turns out that for some people in prod, there are edge case formats that we don't currently handle, which cause errors. 
this workaround safely handles those errors by instead returning the raw timestamp, rather than bugging out.
=> fix: formats dates correctly in the timeline view

pages/_app.tsx
**What**  
We used to only decide the feature flag set on the server side, and trust that it was correct on the client. This re-computes the status of the flags on the client side, and, for now, uses a different value to determine the status of the flag.
=> feat: decide feature flag status on client side

components/FlexibleForms/DateTimeField.module.scss, components/FlexibleForms/DateTimeField.spec.tsx, components/FlexibleForms/DateTimeField.tsx, components/FlexibleForms/FlexibleFields.spec.tsx, components/FlexibleForms/FlexibleFields.tsx, components/FlexibleForms/StepForm.tsx, data/flexibleForms/foo.ts, data/flexibleForms/forms.types.ts, lib/utils.spec.ts, lib/utils.ts, lib/validators.spec.ts, lib/validators.ts, stylesheets/all.scss
this adds support for a combined date and time field to the flexible form builder.
it does this by:
- adding a `<DateTimeField/>` component, and rendering it in `<FlexibleField/>`
- augmenting the `generateFlexibleSchema` and `generateInitialValues` functions to support the new field
- supplementing the `default` attribute on a field to support an array of strings, so a default date and time can be specified like:
```
{
id: 'Date of event',
question: 'When did this happen?',
type: 'datetime',
required: true,
default: [
format(new Date(), 'yyyy-MM-dd'),
format(new Date(), 'HH:00'),
],
},
```
=> feat: datetime field

components/AllocatedWorkers/AllocationRecap/AllocationRecap.spec.tsx, components/AllocatedWorkers/AllocationRecap/AllocationRecap.tsx, components/Cases/CaseRecap/CaseNote.tsx, pages/api/cases/[caseId].ts, utils/api/cases.spec.ts, utils/api/cases.ts
**What**  
When we audit a GET case note by ID request, we also need to provide the resident ID. This adds it as a param to the request. 
**Why**  
[SCT-914](https://hackney.atlassian.net/browse/SCT-914)
=> feat(SCT-914): add resident ID to GET Case Note by ID request

components/NewPersonView/Layout.tsx
**What**  
No ticket, small UX bug fix. Hide the add case note secondary nav button for childrens as case note isn't signed off yet.
=> fix: only show add case note button to adults

components/AddFormDialog/AddFormDialog.spec.tsx, components/AddFormDialog/AddFormDialog.tsx, utils/populate.spec.ts, utils/populate.ts
apparently this is still needed, so i've brought back the old thought-dead code, added some more tests around it.
we should look to eliminate it at the earliest chance, because it's been the source of bugs before
it comprises:
- a `populateChildForm` method which spits out a query string that google interprets to pre-fill particular form fields
- `<AddFormDialog/>` then calls that function if it is rendering a google form
=> feat: bring back google form prefilling

next.config.js, zap-baseline.conf
**What**  
No ticket as a quick enhancement.
Disables next.js "x-powered-by" header raised as a warning by owasp scan
=> Disable "x-powered-by" header

components/Cases/CaseLink.tsx, components/NewPersonView/Event.spec.tsx, components/NewPersonView/Event.tsx, components/NewPersonView/EventLink.spec.tsx, components/NewPersonView/EventLink.tsx, components/NewPersonView/Layout.spec.tsx, components/NewPersonView/Layout.tsx, components/NewPersonView/PersonTimeline.tsx, components/NewPersonView/index.module.scss, package.json, utils/date.spec.ts, utils/date.ts, utils/urls.spec.ts, utils/urls.ts
small improvements to the timeline:
- show a title in all cases, rather than defaulting to "view"
- for **OLDER CASE NOTES ONLY**, show the title or description, if it's available (doing this for newer submissions needs api changes)
- for **OLDER CASE NOTES ONLY**, search case note content as well as name and author
- handle the datetime format returned by google docs
- show a more prominent banner if a person is restricted
=> feat(SCT-918): timeline improvements

components/NewPersonView/Layout.tsx, components/PersonView/PersonDetails.tsx, components/RevisionTimeline/MiniRevisionTimeline.tsx, components/RevisionTimeline/RevisionTimeline.tsx, components/SubmissionsTable/SubmissionRow.tsx, components/pages/people/relationships/view/Relationships.tsx, stylesheets/Section.module.scss, stylesheets/all.scss
minor appearance improvements to the person view, including:
- consistent header to relationships tab
- larger "edit" and "add" links
- new clickable phone numbers and "get directions" links to make personal details more useful
- consistently display dates as elsewhere in the app
- change dates app-wide to eliminate leading zeros (04 Jul 1776 -> 4 Jul 1776)
=> fix: person view appearance tweaks

data/flexibleForms/childCaseNote.ts
**What**  
When 'visit' is selected in the CFS case notes, two questions instead of one now display. The lists within these questions hve been changed to radios instead of checkboxes. Office visit has also been renamed to virtual visit.
**Why**  
Request from CFS
=> split visit types into two queations

components/FlexibleAnswers/FlexibleAnswers.module.scss
answers that spread onto new lines, with `\n` characters, will now be preserved in the `<FlexibleAnswers/>` component, resulting in a better reading experience.
we use the `white-space: pre-wrap` css property to achieve this:
> Whitespace is preserved by the browser. Text will wrap when necessary, and on line breaks
=> fix(sct-919): preserve newlines in flexible answers

lib/allocatedWorkers.spec.ts, lib/allocatedWorkers.ts, lib/cases.spec.ts, lib/cases.ts, lib/postcode.spec.ts, lib/postcode.ts, lib/relationships.spec.ts, lib/relationships.ts, lib/residents.spec.ts, lib/residents.ts, lib/submissions.spec.ts, lib/submissions.ts, lib/teams.spec.ts, lib/teams.ts, lib/warningNotes.spec.ts, lib/warningNotes.ts, lib/workers.spec.ts, lib/workers.ts, pages/login.tsx, utils/auth.ts
**What**  
Turns out destructuring `process.env` can cause issues due to webpack configuration. I haven't dived too deeply into the why but an easy solution is to access properties directly.
https://github.com/vercel/next.js/issues/15574
**Why**  
To resolve bug from screenshot below.
=> remove all cases of destructuring process.env

components/NewPersonView/UnfinishedSubmissions.tsx, components/SubmissionsTable/SubmissionDetailDialog.spec.tsx, components/SubmissionsTable/SubmissionDetailDialog.tsx, components/SubmissionsTable/SubmissionPanel.tsx, lib/submissions.spec.ts, lib/submissions.ts
not all submissions follow the standard `/submissions/:id` url format any more. case notes, in particular, don't.
at the moment, it's possible to go to a task list version of the case note from the dashboard, which shouldn't be possible, because of this.
this pr adds a `generateSubmissionUrl` method that can handle those exceptions.
=> fix: canonical submission urls on the dashboard

components/ApprovalWidget/ApproveDialog.spec.tsx, components/ApprovalWidget/ApproveDialog.tsx, components/ApprovalWidget/PanelApproveDialog.spec.tsx, components/ApprovalWidget/PanelApproveDialog.tsx, components/ApprovalWidget/RejectDialog.spec.tsx, components/ApprovalWidget/RejectDialog.tsx
https://hackney.atlassian.net/browse/SCT-946
improves user experience by refreshing the page after a submission changes state, making sure that the ui reflects the latest state (eg. approved, in progress, submitted)
=> fix(SCT-946): reload after approval, panel approval or reject

data/flexibleForms/childCaseNote.ts
Too small to need description. See title.
=> fix: only ask if children alone after confirming children were seen

data/flexibleForms/adultCaseNote.ts, data/flexibleForms/forms.types.ts, jest.config.js, lib/submissions.spec.ts, lib/submissions.ts, pages/api/case-note/[id].ts, pages/api/submissions/[id]/steps/[stepId].tsx, pages/people/[id]/case-note.tsx, pages/submissions/[id]/steps/[stepId].tsx
**What**  
Allows our flexible forms to identify a field as being the `dateOfEvent`, when patching our answers we then can supply the datetime value from the form.
**Why**  
For our ASC case note form the date of event is currently just when the form was created but the event happened sometime in the past. This then messes up the timeline for the resident for example where the form appears in the timeline when it was created, not when the event occurred.
=> feat(SCT-961): record date of event from asc form

components/SubmissionsTable/SubmissionPanel.spec.tsx, components/SubmissionsTable/SubmissionPanel.tsx, components/SubmissionsTable/index.spec.tsx, components/SubmissionsTable/index.tsx, data/flexibleForms/foo.ts, data/flexibleForms/forms.types.ts
it's ideal to be able to type in the name of a form on the dashboard and see the submissions that match it.
> the filter field on the submissions page seems to work strangely. for instance, if i type “review” it filters out the review 3c forms (meaning, they no longer show) in “just mine” but i see other people’s in “everyone”
this wasn't possible before because we were just querying what came back from the api, which had only the machine-readable `formId`.
- we now use a memoised function to add the form to each submission, before applying searching logic
- we modify components lower down the tree to use the form that already exists, rather than re-searching for it
=> fix: add form data to submissions earlier on, so we can search on it

jest.config.js, lib/submissions.spec.ts, lib/submissions.ts
**What**  
We were mistakenly sending the minutes from the input datetime as seconds, this fixes that
=> Fix: Parse datetime correctly from FlexibleForms

components/GroupRecording/__snapshots__/GroupRecordingWidget.spec.tsx.snap, components/PersonWidget/PersonWidget.spec.tsx, components/PersonWidget/PersonWidget.tsx, components/PersonWidget/__snapshots__/PersonWidget.spec.tsx.snap
**What**  
When a person's address is updated, the change is reflected in the UI when viewing the person details page. If previous addresses were saved on the person and you created a new case note or submission, the address displayed in the widget was not the same as the one found on the details page.
**Why** 
When creating a new case note or submission, the widget pulled the first address from this list of addresses for a person, and the first address may not always be the most recent address saved on a person.
This changes the code to retrieve the address we want to use when a person has a list of addresses associated with them and gets the last address added instead of the first.
We also added `data_test_id` attributes to make testing the change easier.
=> Fix: Address mismatch between creating a new note and a person's details

lib/submissions.ts, pages/people/[id]/case-note.tsx
**What**  
We were always sending the formId as `child-case-note` even when the form was actually for an adult so should be `child-case-note`
**Why**  
Bug fix.
=> Fix: Send correct formId for case notes

components/NewPersonView/PersonTimeline.spec.tsx
**What**  
The `PersonTimeline.spec.tsx` `renders a list of clickable submissions` test started failing. This is due to the testing an output from the function `safelyFormatDistanceToNow`. Now refers to the current time, the test wasn't mocking out the current time though so this test has started failing, added a mock to Date.now that fixes this.
**Why**  
We want our test to actually work and not block the pipeline :p
=> Fix: Person timeline test failing as tested value is dynamic from the date

components/Search/Search.jsx, components/Search/forms/SearchCasesForm.spec.tsx, components/Search/forms/SearchCasesForm.tsx
The date input on search has a bug which reverses the date and month inputs when sent to the back end. 
This input may be replaced with a date picker. The search functionality may have a overhaul in the future. Therefore, we have decided to comment out an not use the date input until we have a clearer way of moving forward with search.
=> Sct 425/chore remove date search

components/PersonWidget/PersonWidget.spec.tsx, components/PersonWidget/PersonWidget.tsx, types.ts
After fixing the initial issue in #641, there was still a case where if the person was updated to have no address (i.e they had an address before but were later updated to have no address in the UI), the widget would still display the most recently added address.
From investigating the data we use in the widget, the response is from the GET all residents endpoint and we filter by the person. The data returned is different as this response would also return an array of all the addresses associated with the person. But to determine the current address, the addresses in the list have a flag associated with them that tells us if this is the display address i.e current active address or if it is an old address.
This changes the logic to retrieve the address that has the flag set to true which …
=> Fix (SCT-982): Address mismatch on widget v2

lib/submissions.spec.ts, lib/submissions.ts, pages/api/submissions/index.ts, pages/work-in-progress.tsx
**What**  
To match the changes in the API from PR https://github.com/LBHackney-IT/social-care-case-viewer-api/pull/405
**Why**  
So code relying on getting unfinished submissions continues to work
This requires some level of simultaneous deployment with the BE changes!
=> Fix: Update API call for in-progress submissions

lib/submissions.spec.ts, lib/submissions.ts
We seem to be hitting a limit on the size of the response from the API, this should limit the amount to submission created in the last two weeks as a temp fix.
=> Fix: Update endpoint call to request for in-progress submissions created two weeks from today

components/NewPersonView/EventLink.spec.tsx, components/NewPersonView/EventLink.tsx, types.ts
**What**  
Frontend is now using the form name for the Casenote title and correctly mapping the form id.
**Why**  
=> Fix(SCT-983): Title handling

data/flexibleForms/adultCaseNote.ts, data/flexibleForms/childCaseNote.ts, data/flexibleForms/forms.types.ts, lib/submissions.spec.ts, lib/submissions.ts, pages/api/case-note/[id].ts, pages/people/[id]/case-note.tsx
**What**  
API can now handle title as can EventLink component for displaying. We now just need to ensure when our flexible form has a title field we capture the value and submit it to the API to store the title of the form.
**Why**  
Better display on the person timeline, instead of just saying "Case note" can say "Case note - whatever the title is"
=> feat(SCT-983): Submit title with form answers

components/NewPersonView/Layout.tsx, data/flexibleForms/childCaseNote.ts, data/googleForms/childForms.ts
**What**  
These changes make it that the new CFS case note (and for visits) form will be displayed to children social care workers.
**Why**  
To take advantage of the forms being integrated into our system and not using google forms.
=> Feat(SCT-519,SCT-773): Activate CFS case note

.circleci/config.yml, ci-scripts/validate-pr-title.js, ci-scripts/validate-pr-title.spec.js, package.json
**What**  
To help us keep release notes accurate and complete, it helps when our PR titles and the associated merge commit follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) pattern. This PR introduces a CI script for validating PR titles, and failing if they do not match the pattern.
=> feat: adds CI script for validating a PR title conforms to conventional commits

lib/validators.spec.ts, lib/validators.ts
**What**  
Update validation for datetimes that must be in the past, can accept a future time if date is past.
**Why**  
To allow for visits/casenotes to record datetimes properly!
=> fix: datetime validate time correctly

components/NewPersonView/PersonTimeline.tsx, components/NewPersonView/UnfinishedSubmissions.tsx, lib/submissions.spec.ts, lib/submissions.ts, pages/api/submissions/index.ts, pages/people/[id]/index.tsx, utils/api/submissions.spec.ts, utils/api/submissions.ts
**What**  
A bunch of our API calls were doing filtering by taking the response and then calling `.filter`. Instead we now pass filter values into our query parameters so that the filtering can be done server side.
**Why**  
Benefits include
- cleaner code
- smaller response size when requesting data
- will work better with pagination, how can you filter correctly if you only return a paginated subset of data
- Have you added any new third-party libraries? no
- Are any new environment variables or configuration values needed? no
- Anything else in this PR that isn't covered by the what/why? no
=> feat(SCT-1076): Use query params to filter submissions server side

components/CaseStatus/CaseStatusView.spec.tsx, components/CaseStatus/CaseStatusView.tsx, factories/caseStatus.ts, types.ts
**What**  
This PR tidies up the main UI visualization for Case Status Types.
Style changed a bit as well
**Why**  
Before this, in presence of multiple case status connected to the user, they were displayed all under the user's name, one per subtype.
Now it displays only the main status type. 
A following PR will add the main component which will hold the detailed information
=> feat(SCT-1100): Display case statuses

components/Cases/CaseLink.tsx, components/NewPersonView/EventLink.tsx, components/NewPersonView/UnfinishedSubmissions.spec.tsx, components/NewPersonView/UnfinishedSubmissions.tsx, components/SubmissionsTable/SubmissionPanel.spec.tsx, components/SubmissionsTable/SubmissionPanel.tsx, components/SubmissionsTable/index.tsx, data/flexibleForms/forms.types.ts, data/flexibleForms/mapFormIdsToFormDefinition.ts, lib/submissions.ts, pages/api/submissions/[id]/index.ts
**What**  
Utilise our mapping form id to form object.
Remove form property from our submissions as it is no longer added via mutation at the API level.
**Why**  
We want to show the actual percentage complete or handle errors appropriately when we can not compute % complete.
=> fix(SCT-1126): nan percent complete showing in unfinished submissions

components/NewPersonView/PersonHistory.spec.tsx, components/NewPersonView/PersonHistory.tsx, components/NewPersonView/PersonTimeline.spec.tsx, components/NewPersonView/PersonTimeline.tsx, components/NewPersonView/UnfinishedSubmissions.spec.tsx, components/NewPersonView/UnfinishedSubmissions.tsx
**What**  
Fix showing the correct form name instead of the form id (i.e says "Case note" instead of "adult-case-note"
Handle all different states, loading state, error state, no results.
Test all these states and correct form name shown.
Test we call useUnfinishedSubmissions with correct person id.
Tidy up PersonHistory and PersonTimeline components.
**Why**  
Tidy up code.
Handle error better/loading.
More complete testing.
=> fix(SCT-1134): Test and improve unfinished submissions

.release-it.json
**What**  
Specify the types wanted in our release notes and enable `chore` and `docs`, following [Conventional Changelog Configuration Spec (v2.1.0)](https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md#types) which is pointed to in the [Conventional Changelog plugin for release-it's docs](https://github.com/release-it/conventional-changelog#preset).
**Why**  
We're seeing empty release notes e.g. [v0.23.1](https://github.com/LBHackney-IT/lbh-social-care-frontend/releases/tag/0.23.1) and it seems it's because `chore` and `docs` are hidden by default. 
- Anything else in this PR that isn't …
=> fix: chores and documentation not showing in release notes

lib/caseStatus.spec.ts, lib/caseStatus.ts
[SCT-1555](https://hackney.atlassian.net/browse/SCT-1155)
Case status endpoint names have various way of spelling "case status".
This PR aligns them to "case-statuses"
`${ENDPOINT_API}/residents/${personId}/casestatuses` becomes `${ENDPOINT_API}/residents/${personId}/case-statuses`
`${ENDPOINT_API}/case-status/form-options/${type}` is now `${ENDPOINT_API}/case-statuses/form-options/${type}`
=> fix(SCT-1155): Align endpoint names

components/Cases/CasesTable.tsx, components/Search/Search.jsx
**What**  
Some frontend logic exists for sorting by column name and if the sort should be ascending or descending. At the current moment though we don't ever sort these tables so I have deleted the code as it adds complexity without any functionality.
**Why**  
Cleaner code/Less code == less bugs maybe
=> fix: Remove sorting logic for tables that is never actually used

components/NewPersonView/Layout.tsx, components/NewPersonView/UnfinishedSubmissions.tsx
**What**  
^ should not be showing the 0...
**Why**  
It's a mistake, JSX if check meant to be comparing length and only showing unfinished submissions when the length is greater than 0, when you do something like 
```
{unfinishedSubmissionRes?.items?.length && ...}
```
in JSX if the left side of the && expression is true the right side JSX will get rendered, however if the left side is false(y) it actually displays 0, what you need to do is 
```
{unfinishedSubmissionRes?.items?.length > 0 && ...}
```
However, in this case we didn't even need the length check, if the length is 0 then we map over an empty list and render nothing which allowed reduction in nested if clauses.
- Are any new environment variables or …
=> fix: Unfinished submissions showing 0 for no reason when there are no submissions

components/NewPersonView/Layout.tsx, components/NewPersonView/UnfinishedSubmissions.spec.tsx, components/NewPersonView/UnfinishedSubmissions.tsx, lib/submissions.ts, pages/api/submissions/index.ts, utils/api/submissions.spec.ts, utils/api/submissions.ts
**What**  
Make a sensible paginated request for unfinished submissions as we currently only display 4.
**Why**  
Before
After
Admittedly I hope there aren't people on the system with 100's (242) of unfinished submissions like this staging user.
http://dev.hackney.gov.uk:3000/people/1
See a 89% decrease in response time.
See a 96% decrease in response size.
=> fix: Fetch unfinished submissions as paginated

package.json, yarn.lock
Dependabot raised a security alert [here](https://github.com/LBHackney-IT/lbh-social-care-frontend/security/dependabot/yarn.lock/set-value/open) about the set-value package needing an upgrade to a version that has been patched to fix a vulnerability.
It seems Dependabot was unable to do this automatically, so this PR manually attempts to fix the issue raised.
=> chore: Upgrade set-value to version 4.0.1 or later

components/CaseStatus/CaseStatusDetails.spec.tsx, components/CaseStatus/CaseStatusDetails.tsx, components/CaseStatus/CaseStatusView.spec.tsx, components/CaseStatus/CaseStatusView.tsx, components/NewPersonView/Layout.tsx, factories/caseStatus.ts, lib/caseStatus.ts, types.ts, utils/api/caseStatus.ts
**What**  
Response type from the API has changed when calling GET api/v1/case-statuses/{personId}
This PR updates our expected response from the API and handles the new data accordingly as well as updates related tests.
=> fix: update return type when getting case statuses by person id

components/CaseStatus/AddCaseStatusForm/AddCaseStatusForm.spec.tsx, components/CaseStatus/AddCaseStatusForm/AddCaseStatusForm.tsx, components/CaseStatus/AddCaseStatusForm/ReviewAddCaseStatusForm.spec.tsx, components/CaseStatus/AddCaseStatusForm/ReviewAddCaseStatusForm.tsx, data/flexibleForms/caseStatus.ts, types.ts, utils/api/caseStatus.spec.ts, utils/api/caseStatus.ts
**What**  
This adds changes that would allow a user to add a CP case status with a specific category to a child resident.
**Why**  
Users want to be able to add and view a CP case status saved on a child resident.
=> feat(SCT-1055): Add CP option to the case status add form UI

components/CaseStatus/CaseStatusDetails.tsx
**What**  
This adds a condition for when the case status array is empty.
**Before**
**After**
**Why**  
The details page would show the case statuses title even if there were no case statuses. This checks if the array is empty as well as if it's undefined before returning the UI for case statuses.
=> chore: When case status array is empty, don't show the case status title

lib/validators.ts
**What**  
I've added a check for a start_date in the previous release which checks if the date is in the past.
This check does not work properly so I'm pushing a quick fix for this - it was not checking if the date was undefined, only null, thus failing
**Why**  
To fix the Start Date component in the date picker
=> fix: start date validator

zap-baseline.conf
**What**  
Application of [PR 696](https://github.com/LBHackney-IT/lbh-social-care-frontend/pull/696) means that 
`10202	WARN	(Absence of Anti-CSRF Tokens)` now passes so the scan rule can be upgraded from `WARN` to `FAIL`.
=> chore: Make zap fail on absence of anti csrf tokens

.circleci/config.yml
**What**  
Add further scanning to the baseline security scan by enabling the Ajax spider **in addition** to the traditional one.
=> feature: Use ajax spider in addition to traditional zap baseline scan

components/OnboardingDialog/index.spec.tsx, components/OnboardingDialog/index.tsx
**What**
Update onboarding dialog to open the roadmap link in a new tab.
**Why**  
It's an external page and so the user doesn't have to go back to the application.
=> feat: update onboarding dialog to open link in a new tab

components/CaseStatus/AddCaseStatusForm/ReviewAddCaseStatusForm.tsx, pages/api/casestatus/[id]/index.ts, pages/api/casestatus/index.ts, pages/api/casestatus/update/[caseStatusId]/index.ts
**What**  
Next.JS API routes now returns correctly Case Status error messages sent from the backend to the frontend.
The error definitions are passed from the API routes to the try/catch block when calling the endpoint.
**Why**  
Before this it wasn't clear what the error was when an operation went wrong - all that was displayed was the error number, which doesn't make much sense to the end user.
=> fix(SCT-1362): Case Status error handling in UI

components/NewPersonView/Layout.spec.tsx, components/NewPersonView/Layout.tsx
**What**  
Update the `Workflows` link on a person's page to default to showing historic workflows.
**Why**  
We're importing historic workflows and want them to show by default when a person goes to see their workflows.
=> feat: update workflows link on person's page to show historic workflows

components/MashCards/MainCard.tsx, components/MashDashboard/MashDashboard.tsx, pages/mash-referral/[id]/screening-decision.tsx
**What**  
Allows the tab within team-assignment to be selected based on query params from the URL.
This allows linking to the page with a tab open.
Enables us on completion of a mash action such as screening decision to redirect the user back to the team-assignments page with the screen decision tab being open.
**Why**  
Slightly better than contact always being pre-selected on laoding team-assignments page.
Will enable us in a follow up PR to show a confirmation component after the direct from the action page.
=> feat(SCT-1436): query param to pre select mash dashboard tab

components/MashDashboard/MashDashboard.tsx, factories/mashReferral.ts, lib/mashReferral.ts, pages/api/mash-referral/[id]/index.ts, pages/mash-referral/[id]/initial-decision.tsx, pages/mash-referral/[id]/screening-decision.tsx, types.ts, utils/api/mashReferrals.ts
**What**  
Create a form for initial decision that when completed submits the data to the API, on 200 response redirect user back to team assignments page in the inital-decisions tab, see the referral has moved into screening tab.
**Why**  
Important part of Mash Referral workflow.
=> feat(SCT-1420): Action page for initial decision

components/MashCards/ContactCard.tsx, components/MashCards/FinalDecisionCard.tsx, components/MashCards/InitialDecisionCard.tsx, components/MashCards/ScreeningCard.tsx
**What**  
Minor changes to the initial decision card so it matches the designs from figma
https://www.figma.com/file/Mw7tNmwNUGzpZDBXMaGhAj/MASH?node-id=5%3A2
=> fix(SCT-1444): intial decision card to match designs

cypress/integration/case_status.ts, pages/people/[id]/case-status/[caseStatusId]/edit/edit.tsx, pages/people/[id]/case-status/[caseStatusId]/update/edit.tsx
**What**  
If changing the start date of the current case status, will affect the end date of the previous case status. 
Adding an Announcement box to alert the user of this.
**Why**  
This announcement box is to make this fact more explicit to the user.
Separate but related, I added an E2E Cypress test for displaying an announcement box on the LAC Update page when making a scheduled case status and there is a pre-existing scheduled case status
=> feat(SCT-1378): add EDIT announcement for changing case status start date consequences

components/CaseStatus/EditCaseStatusForm/ReviewEditCaseStatusForm.tsx, components/CaseStatus/UpdateCaseStatusForm/ReviewUpdateCaseStatusForm.tsx, types.ts
**What**  
Added support for type `Multiple` for case status type CP
Added error handling in the FE for failed operations
**Why**  
The data imported from Mosaic contained this case status type for CP, we need to support it.
Some bits of the FE were not receiving the correct error message to be handled.
=> feat(SCT-1469): "Multiple" type + error handling

components/NewPersonView/Event.spec.tsx, components/NewPersonView/EventLink.spec.tsx, components/NewPersonView/EventLink.tsx, components/NewPersonView/PersonHistory.spec.tsx, components/NewPersonView/PersonTimeline.spec.tsx, types.ts
modify timeline events to correctly show workflows:
- detect whether a case represents a workflow by looking for a `workflowId` string in `caseFormData`
- use a link `href` that correctly links to the pilot app
- show the correct name of the assessment/form type
=> feat: workflow pilot on timeline

components/MashForms/FinalDecisionForm.spec.tsx, components/MashForms/FinalDecisionForm.tsx, lib/mashReferral.ts, pages/api/mash-referral/[id]/index.ts, pages/mash-referral/[id]/final-decision.tsx, utils/api/mashReferrals.ts
**What**  
Pass in required props to our FinalDecisionForm
Hitting submit on final decision form now submits answers to the API. API is not setup to handle the incoming data yet and update the referral.
Handle error and submitting state.
**Why**  
The form actually needs to be able to submit data to the backend...
=> feat(SCT-1505): final decision form to submit answers to api

components/MashDashboard/MashDashboard.tsx, lib/mashReferral.ts, pages/api/mash-referral/reset.ts, utils/api/mashReferrals.ts
This is just for testing purposes, allow staff to easily hit reset endpoint to revert all the staging dummy data.
=> feat: reset button for dummy data

components/CaseStatus/CaseStatusFlag/CaseStatusFlag.tsx
**What**  
The URL now uses a relative path so it doesn't matter if we're in dev/staging/prod, the link will always work
**Why**  
The Case Status flag had the development link hardcoded in the link, making it useless on production.
=> fix(SCT-1523): removed hardcoded URL from case status flag

serverless.yml
**What**  
Switcharoo domain names for production in serverless config to get them using the right Cloudfront distributions.
**Why**  
To enable the frontend migration to Mosaic-Production. 
=> feat: switch around aliases for production in serverless config

serverless.yml
**What**  
Update the CloudFront alias for production to be something that is non-existent.
**Why**  
We want to switch around the domain names attached to CloudFront distributions in ProductionAPIs and Mosaic-Production but can't because they're both attached to a distribution. As a result, we need to point production to something non-existent, deploy that to remove the association and then deploy to Mosaic-Production to switcharoo.
=> feat: update CloudFront alias for production to be non-existent

components/CaseStatus/EditCaseStatusForm/ChooseEditCaseStatusForm.spec.tsx, components/CaseStatus/EditCaseStatusForm/ChooseEditCaseStatusForm.tsx, components/CaseStatus/EditCaseStatusForm/EditCaseStatusForm.spec.tsx, components/CaseStatus/UpdateCaseStatusForm/ReviewUpdateCaseStatusForm.tsx, components/CaseStatus/UpdateCaseStatusForm/UpdateCaseStatusForm.spec.tsx, components/CaseStatus/UpdateCaseStatusForm/UpdateCaseStatusForm.tsx, components/NewPersonView/Layout.tsx, cypress/integration/case_status_CP.ts, data/flexibleForms/caseStatus/chooseEdit.ts, data/flexibleForms/caseStatus/endCaseStatus.ts, data/flexibleForms/caseStatus/updateCP.ts
[Link to ticket 1](https://hackney.atlassian.net/browse/SCT-1530)
[LInk to ticket 2](https://hackney.atlassian.net/browse/SCT-1532)
**What**  
- CP now can have multiple episodes in the same fashion as LAC
- Removed `X1` from the possible ending reason for LAC
**Why**  
CP needs to record episodes in the same way LAC does
X1 for LAC is not selectable by the user, but se automatically by the system when the child circumstance changes
=> feat(SCT-1530, SCT-1532): Case Status pre-launch flow fix UI

components/NewPersonView/Event.spec.tsx, components/NewPersonView/Event.tsx, cypress/integration/delete_case_note.ts, data/flexibleForms/forms.types.ts, factories/cases.ts, types.ts, utils/api/cases.spec.ts
[Link to ticket ](https://hackney.atlassian.net/browse/SCT-1348)
**What**  
- Added extra information to a deleted case notes in the timeline
- Added tests
- Enabled some Case Note deletion test that were disabled by mistake
**Why**  
We need to display the deletion extra information in the timeline (requested by / date / reason for deletion)
=> feat(SCT-1348): Added description to deleted case notes in timeline

features.ts
**What**  
Some of the features flags had expiry dates that had passed or were close. These dates have been extended to 31/01/2022.
**Why**  
When we pass the expiry date on the feature flags, the main pipeline fails and it is not possible to deploy to production
=> fix(SCT-1346): Extend feature flags

components/RevisionTimeline/RevisionTimeline.spec.tsx, components/RevisionTimeline/RevisionTimeline.tsx, cypress/integration/delete_case_note.ts
**What**  
Have added in a 'Deleted by' history point to deleted case note records
**Why**  
This keeps the interface consistent and provides additional information when on a specific case note
Have added an additional e2e test to confirm this works as expected
=> feat(SCT-1552): Add deleted information to case note history

components/AddFormDialog/AddFormDialog.spec.tsx, components/AddFormDialog/AddFormDialog.tsx, components/Dashboard/DashboardWrapper.spec.tsx, components/Dashboard/DashboardWrapper.tsx, components/Dashboard/__snapshots__/DashboardWrapper.spec.tsx.snap, components/Layout/index.spec.tsx, components/Layout/index.tsx, components/NewPersonView/Layout.spec.tsx, components/NewPersonView/Layout.tsx, features.ts
**What**  
Remove the workflows pilot feature flag.
**Why**  
In preparation of pilot launch, we created the feature flag. We're now post-pilot so the feature flag is always active and no longer valuable.
=> chore: remove workflows pilot feature flag

components/RevisionTimeline/RevisionTimeline.spec.tsx
Better test for Revision Timeline deleted record
**What**  
-Edited a test so it's cleaner / neater
**Why**  
The `queryByText` function with some parameters were not testing the correct items, but tests were passing anyways.
=> fix: Revision Timeline tests

.circleci/config.yml
**What**  
Update our pipeline so unit tests and the E2E tests and OWASP scan run in parallel.
**Why**  
Should speed ⚡ the pipeline up as we don't have to wait for the unit tests to finish before doing the build then E2E tests and security scan.
- Before this change, running the pipeline for a PR takes approximately 10 minutes. 
- After this change, running the pipeline for a PR takes approximately 8 minutes. 
=> refactor: run E2E tests and OWASP scan in parallel of unit tests in pipeline

serverless.yml
**What**  
-Removed "~true" from variable ssm link
-added "variablesResolutionMode" parameter set to `20210326`
**Why**  
Serverless recently returned this error:
```
Serverless: Checking Stack update progress...
....... 
Serverless Error ----------------------------------------
The security token included in the request is expired
Get Support --------------------------------------------
Docs:          docs.serverless.com
Bugs:          github.com/serverless/serverless/issues
Issues:        forum.serverless.com
Your Environment Information ---------------------------
Operating System:          linux
Node Version:              14.17.5
Framework Version:         2.69.1
Plugin Version:            5.5.1
SDK Version:               4.3.0
Components Version:        3.18.1
Serverless: Deprecation …
```
=> fix: Serverless ssm parameters

components/WarningNotes/ReviewWarningNoteForm/ReviewWarningNoteForm.spec.tsx
We had a bug with a test that used a date of Jan 2nd 2022, which worked until the world ticked past Jan 2nd 2022, then it started failing.
This switches that test to use a dynamically generated date instead!
=> fix: resolve issue with date in review warning note tests

package.json, yarn.lock
**What**  
Upgraded `release-it` package to the latest version
**Why**  
Dependabot marked one of its dependencies as a vulnerability
=> fix(SCT-1639): Fix dependabot dependencies

next.config.js
**What**  
We want to preserve the code and redirect calls from team assignment pages to root.
**Why**  
Mash referrals are cancelled.
=> chore: added redirects to root for all team assignment calls

.circleci/config.yml
**What**  
Small PR to remove SENTRY_RELEASE from the circleci config file
**Why**  
This is the final step to revert the Sentry changes on the main branch
=> chore(SCT-1279): Remove SENTRY_RELEASE from circleci config

features.ts
**What**  
Have extended the todo expiry dates that are set on two of the feature flags
**Why**  
The expiry date on these items had passed but we still want these feature flags in place. Since the todo date has passed our linting fails
=> chore: Push todo expiry dates

cypress/plugins/index.js, cypress/support/commands.ts, package.json, utils/auth.ts
**What**  
add an explicit session expiration time value of `14400` to auth config
**Why**  
using the same value as the core pathway app means that people will stay logged into both for the same amount of time. 
at the moment, core pathway app is stricter, so someone can be logged into the mainstream tool and be prompted to log in again to access core pathway data, which is confusing and frustrating.
=> chore: use an explicit session expiration time

serverless.yml
**What**  
Update serverless config to use the new sub domain specific SSL certificate instead of the Hackney wildcard one. 
**Why**  
Hackney wildcard SSL certificate expires on 10/02/22, so we need to update the config to use new certificate.
=> feat(SCT-1685): update SSL certificate used on staging

components/Dialog/Dialog.tsx, components/FlexibleAnswers/FlexibleAnswers.tsx, components/ResidentPage/CaseNoteDialog.module.scss, components/ResidentPage/CaseNoteDialog.spec.tsx, components/ResidentPage/CaseNoteDialog.tsx, components/ResidentPage/CaseNoteGrid.spec.tsx, components/ResidentPage/CaseNoteGrid.tsx, components/ResidentPage/CaseNoteTile.spec.tsx, components/ResidentPage/CaseNoteTile.tsx, components/ResidentPage/RemoveCaseNoteDialog.tsx, components/ResidentPage/WorkflowTree.tsx, pages/residents/[id]/case-notes.tsx, pages/residents/[id]/index.tsx
at the moment, users hate how slow it is to navigate through case notes. they have to open new tabs and painstakingly move through them to find what they need.
something they've asked for several times is previous/next navigation on notes.
this refactors the case note interface into dialogs that users can "peek" into quickly, with:
- the open note represented in the url so it can be shared
- left/right keyboard navigation for skipping through notes quickly
- a link to the existing, full-page "printable version" if the user wants
- 
works well with:
- modern case notes (submissions)
- traditional case notes (records)
- google form submissions
- audit trail events
one limitation of this approach is that it can only skip through the portion of case note/record data that's been loaded by the …
=> feat: case note dialogs

serverless.yml
**What**  
Update SSL certificate ARN used for mosaic-production account
**Why**  
This will update the production site to use the new SSL certifcate that was generated to replace the current and soon to be expiring wildcard certificate.
=> feat(SCT-1687): update ssl cert arn for mosaic production

components/ResidentPage/CaseNoteGrid.spec.tsx, components/ResidentPage/CaseNoteGrid.tsx, components/ResidentPage/Collapsible.module.scss, components/ResidentPage/WorkflowTree.spec.tsx, components/ResidentPage/WorkflowTree.tsx, lib/permissions.ts, pages/residents/[id]/case-notes.tsx, pages/residents/[id]/index.tsx, pages/residents/[id]/workflows.tsx, zap-baseline.conf
the new resident view now respects the `restricted` flag on a resident, like the current live person view.
also, `restricted` is extended to treat workflows the same way, not just case notes/records.
=> chore: new resident view respects restricted

components/ResidentPage/CaseNoteDialog.module.scss, components/ResidentPage/CustomAddressEditor.module.scss, components/ResidentPage/CustomAddressEditor.spec.tsx, components/ResidentPage/CustomAddressEditor.tsx, components/ResidentPage/CustomPhoneNumberEditor.module.scss, components/ResidentPage/CustomPhoneNumberEditor.spec.tsx, components/ResidentPage/CustomPhoneNumberEditor.tsx, components/ResidentPage/DataBlock.tsx, components/ResidentPage/InlineEditor.tsx, pages/residents/[id]/index.tsx, types.ts
the default in-place editor can cover text fields and select fields, but some more complicated fields need something special.
so, this adds two new components:
- `<CustomPhoneNumberEditor/>` with "add another" functionality
- `<CustomAddressEditor/>` with postcode search functionality
=> feat: custom phone address editors

components/NewPersonView/Layout.tsx, components/NewPersonView/PreviewBanner.tsx, components/ResidentPage/CustomAddressEditor.module.scss, components/ResidentPage/CustomAddressEditor.spec.tsx, components/ResidentPage/CustomAddressEditor.tsx, components/ResidentPage/CustomPhoneNumberEditor.module.scss, components/ResidentPage/CustomPhoneNumberEditor.spec.tsx, components/ResidentPage/CustomPhoneNumberEditor.tsx, components/ResidentPage/DataBlock.spec.tsx, components/ResidentPage/DataBlock.tsx, components/ResidentPage/InlineEditor.module.scss, components/ResidentPage/InlineEditor.tsx, components/ResidentPage/Mapping.spec.tsx, components/ResidentPage/Mapping.tsx, components/ResidentPage/WorkflowOverview.tsx, cypress/integration/delete_case_note.ts, features.ts, lib/validators.ts, pages/people/[id]/index.tsx, pages/residents/[id]/index.tsx, stylesheets/all.scss, types.ts
improves the way we validate data for a resident by:
- storing it in one place: a central yup schema in `lib/validators.ts`
- refactoring `<InlineEditor/>` to use formik rather than react-hook-form, so we can make easy use of yup validation
- improving the custom address and phone number editors to display yup error messages too
this should make it much easier to maintain our validation conditions and error messages
o
=> feat: use proper, declarative yup-based validation on the person view

pages/_document.tsx
**What**  
The new NextJS version breaks the font import.
We added them back manually
=> fix: fix font in new NextJS version

pages/_document.tsx
**What**  
The login page is not loading the Google CDN for the font stylesheet.
This is because there's a CSP preventing the script for loading.
This PR adds the nonce to the script so it can be executed correctly.
**Why**  
The login page is not loading the Google CDN for the font stylesheet.
=> fix: Added nonce to stylesheet link

.circleci/config.yml
**What**  
Updates the `build-deploy-staging` and `build-deploy-mosaic-production` jobs to have a build step that sets the value of `NEXT_PUBLIC_CORE_PATHWAY_APP_URL` to be the URL for the deployment environment.
**Why**  
This fixes a bug that involved Staging using a production URL when starting/adding a new workflow.
- This change also involves adding new environment variables: `STAGING_CORE_PATHWAY_APP_URL` and `PRODUCTION_CORE_PATHWAY_APP_URL` to CircleCI
=> fix: Update the pipeline to build before deploying.

cypress/integration/case_status_CIN.ts, cypress/integration/case_status_CP.ts, cypress/integration/case_status_LAC.ts, features.ts
**What**  
As we are not currently using the Case Status functionality, we have removed the functionality by setting the relevant feature flag to 'false'.
We also X'd out the cypress tests for the case statuses for CIN, CP & LAC.
We added new cypress tests here to test for the absence of the case status link
**Why**  
The E2E tests for the case statuses take some time to run so disabling will speed up the build pipeline.
=> fix: disable Case Status via feature flag

components/Dialog/Dialog.tsx, components/ResidentPage/CaseNoteDialog.module.scss, components/ResidentPage/CaseNoteDialog.tsx, components/ResidentPage/CaseNoteGrid.module.scss, components/ResidentPage/CaseNoteGrid.tsx, components/ResidentPage/CaseNoteTile.tsx, components/ResidentPage/CaseOpenness.spec.tsx, components/ResidentPage/CaseOpenness.tsx, components/ResidentPage/Layout.spec.tsx, components/ResidentPage/Layout.tsx, components/ResidentPage/StatusTags.tsx, components/ResidentPage/WorkflowOverview.tsx, data/primarySupportReasons.ts, pages/residents/[id]/allocations.tsx, pages/residents/[id]/index.tsx, utils/contentSecurity.spec.ts, utils/contentSecurity.ts
assorted small tweaks to get resident view shipshape
checked by elsa already
=> chore: new resident view tweaks

.env.sample, components/ErrorBoundary/ErrorBoundary.tsx, components/Layout/index.tsx, components/NewPersonView/PreviewBanner.tsx, features.ts, pages/people/[id]/index.tsx, serverless.yml
**What**  
- This PR re-enables the Preview banner for adults
- <Link> component has been changed to a <a>  component
- Feedback form link is now hardcoded
- The Feature flag has been changed so it's enabled everywhere but production environment.
- Removed `NEXT_PUBLIC_FEEDBACK_LINK` env variable
**Why**  
This PR re-enables the Preview banner for adults after the incident
=> fix: Preview banner

features.ts
bring back preview banner linking to the new resident view
=> chore: bring back resident view v3 preview banner

components/Search/Search.spec.tsx, components/Search/Search.tsx, components/Search/forms/SearchResidentsForm.spec.tsx, components/Search/forms/SearchResidentsForm.tsx, cypress/integration/add_view_and_remove_relationship.ts, cypress/integration/search_for_person.ts, factories/search.ts, lib/search.spec.ts, lib/search.ts, pages/api/search/person/index.ts, types.ts, utils/api/search.spec.ts, utils/api/search.ts
**What**  
* Combined the first name and last name search boxes, so there is now just one person name search box when looking for a person or adding a relationship
* Updated tests to input information into this new search box
* Added new search endpoint that will be used when searching for a person or adding a relationship
**Why**  
This change was made to allow for fuzzy searching on a persons name. This means that users could misspell a person's name and still be able to find the person they are looking for.
This depends on [this PR](https://github.com/LBHackney-IT/social-care-case-viewer-api/pull/595) which adds the new endpoint in the backend
=> feat(SCT-1737, SCT-1738): Refactor frontend to use new search endpoint 

components/Search/forms/SearchResidentsForm.spec.tsx, components/Search/forms/SearchResidentsForm.tsx, components/Tabs/Tabs.spec.tsx, components/Tabs/Tabs.tsx, cypress/integration/search_for_person.ts
**What**  
Update the frontend to have the name person_id for the field used to search for a specific id
**Why**  
The frontend was passing mosaic_id to the new search endpoint, however the end point was expecting person_id
Altered the query that is passed when switching from person search to record search. Now only the person_id will be passed between the two searches
=> fix(SCT-1737): Change from using mosaic_id to person_id in the front end search

utils/api/search.ts
**What**  
Send first and last name separately to search endpoint, API updated under https://github.com/LBHackney-IT/social-care-case-viewer-api/pull/601
**Why**  
Details discussed on ticket, but primarily to allow for more accurate results when giving first and last names.
- Have you added any new third-party libraries? ❌
- Are any new environment variables or configuration values needed? ❌
- Anything else in this PR that isn't covered by the what/why? ❌
=> feat(SCT-1756): stop combining first and last name on search

components/Search/forms/SearchResidentsForm.spec.tsx, components/Search/forms/SearchResidentsForm.tsx
**What**  
https://hackney.atlassian.net/browse/SCT-1766
Allows users to enter a fragment of a postcode, a minimum of two characters is expected.
**Why**  
Now we are bringing back lots of results, users need to be able to filter them on the postcode.
- Have you added any new third-party libraries? ❌
- Are any new environment variables or configuration values needed? ❌
- Anything else in this PR that isn't covered by the what/why? ❌
=> feat(SCT-1766): Allow searching on postcode fragments

components/Search/Search.spec.tsx, components/Search/Search.tsx
**What**  
Show the "add new person" link after at most two clicks of load more.
**Why**  
There is potential for hundreds of results to come back and clicking load more many times just to get to add a new person is no longer suitable.
- Have you added any new third-party libraries? ❌
- Are any new environment variables or configuration values needed? ❌
- Anything else in this PR that isn't covered by the what/why? ❌
=> feat(SCT-1761): show new resident link earlier

components/ResidentPage/Mapping.spec.tsx, components/ResidentPage/Mapping.tsx, components/ResidentPage/StatusTags.module.scss, components/ResidentPage/WorkflowChunk.module.scss, components/ResidentPage/WorkflowChunk.tsx, components/ResidentPage/WorkflowOverview.spec.tsx, components/ResidentPage/WorkflowOverview.tsx, pages/residents/[id]/index.tsx, pagesTest/residents/[id]/index.spec.tsx
=> chore: better empty and initial states for case notes, workflows and maps

components/ResidentPage/CaseNoteDialog.spec.tsx, components/ResidentPage/CaseNoteDialog.tsx
> and, following on from the issue beverley spotted just moments ago: this is related to "historic" case notes, and we're investigating. we'll post here again as soon as we have a solution in place. in the meantime, you can still access the content of the notes via the "printable version" link in the popup.
> I know that there was some user acceptance testing of the resident view but I need to feedback that the casenotes/records are not displayed in a very easy to navigate way. You still have to go back and forth in a record to try and obtain information and some of the records are not visible (until clicking on the printable option).
https://hackit-lbh.slack.com/archives/C021Q88C953/p1648140239855699
=> fix: historic notes

components/Allocations/AddAllocation/AddAllocation.spec.tsx, components/Allocations/AddAllocation/AddAllocation.tsx, components/Allocations/EditAllocationPriority/EditAllocationPriority.spec.tsx, components/Allocations/EditAllocationPriority/EditAllocationPriority.tsx, components/PriorityRating/PriorityRating.spec.tsx, components/PriorityRating/PriorityRating.tsx, factories/allocatedWorkers.ts
**What**  
This PR fixes the values sent by the frontend for the `ragRating` parameter
**Why**  
I'm sending colours, BE is expecting keywords
=> fix: Fix parameter names allocations

components/Allocations/AddAllocation/AddAllocation.tsx, components/Allocations/AddWorkerAllocation/AddWorkerAllocation.tsx, components/Allocations/DeallocateTeamWorker/DeallocateTeamWorker.tsx, components/Allocations/EditAllocationPriority/EditAllocationPriority.tsx, components/PriorityRating/PriorityRating.tsx, pages/residents/[id]/allocations.tsx, pages/residents/[id]/allocations/[allocationId]/allocateworker.tsx, types.ts
**What**  
- Fix redirect to people view on deallocation
- Fix redirect to old person view when editing rag rating.
- Fix setting teamID and allocation date in the url when allocating a worker to an existing team allocation
- If worker not set for allocation do not make get request to get worker details (the request is for the Workers in the team)
- Links in blue 
- Alignment of “deallocate worker“
**Why**  
To complete the Worker Allocation flow
=> fix: Fixes for allocations

pages/residents/[id]/allocations.tsx, types.ts
**What**  
Expected parameter for Allocations has been changed from `teamId` to `allocatedWorkerTeamId `
**Why**  
This is needed to align the FE with the BE
=> fix: Change allocatedWorkerTeamId parameter name

pages/residents/[id]/allocations.tsx
**What**  
Makes it more clear which worker is allocated to the resident for worker only allocations.
**Why**  
Because team allocations show the team, worker only allocations should show the worker.
=> fix: Add worker name for worker only allocations

lib/allocatedWorkers.spec.ts, lib/allocatedWorkers.ts
**What**  
This PR removes an unnecessary Allocations at FE API level.
The correct URL parameter is now sent as an URL parameter in the request
**Why**  
The Allocations loaded in the FE are filtered by "closed" status and "allocationEndDate".
This is an issue because the BE is sending only 20 rows (not all) and the FE is doing the filtering, so it's not entirely clear what's going on "under the hood"
This filter should be in the BE, and the 20 rows limit removed.
This PR should be merged after that happens.
=> fix: Removed FE filter for closed allocations

components/PriorityRating/PriorityRating.spec.tsx, components/PriorityRating/PriorityRating.tsx, pages/residents/[id]/allocations.tsx
**What**  
This PR lets us add a priority level for legacy allocations (created without ragRating in the previous versions)
**Why**  
Before this there was no way on editing a ragRating for legacy applications
=> feat: RagRating for legacy allocations

components/NewPersonView/Layout.tsx, lib/formatters.spec.ts, lib/formatters.ts
**What**  
This PR fixes the displayed allocation in the header.
Code has been optimised as it was copy/pasted multiple time
Tests added
**Why**  
It was not supporting team-only allocation, so it was saying "Allocated to undefined" 
- Have you added any new third-party libraries? X 
- Are any new environment variables or configuration values needed? X 
=> fix: allocation summary in header

components/Allocations/DeallocateTeamWorker/DeallocateTeamWorker.tsx
**What**  
This PR adds a `deallocationScope` parameter in the deallocateAllocation request.
This parameter can be either `worker` or `team` and it's placed in the body of the request
**Why**  
The BE will differentiate what to deallocate based on this parameter
=> feat: Added deallocationScope to dealllocation request object

components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.spec.tsx, components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.tsx, components/AllocatedWorkers/DeallocateWorker/DeallocateWorker.tsx
**What**  
This PR adds the necessary parameters for Children to add and remove allocations from the /people/{id}/allocations page
**Why**  
The structure of the (de)Allocation request in the BE has changed, but the /people/{id}/allocations form doesn't work as it uses the old request object.
- Have you added any new third-party libraries? X
=> fix(SCT-1795): Added necessary parameters for children allocations/deallocations

components/ResidentPage/InlineEditor.spec.tsx, components/ResidentPage/InlineEditor.tsx, package.json, pages/api/residents/[id]/index.ts, utils/api/residents.ts
**What**  
Updated inline editor to use a new PATCH endpoint
This will now only send edited information to the PATCH endpoint
**Why**  
We want to make use of a new PATCH endpoint that will update only edited information so that invalid fields do not prevent updating details
=> fix: Updating inline editor to use new PATCH endpoint

pages/residents/[id]/index.tsx, pagesTest/residents/[id]/index.spec.tsx
prevents a simple privilege escalation attack where a non-admin user could change a restricted resident to unrestricted.
now, the restricted control is read-only unless the user is sufficiently powerful
=> chore: only proper people can change restrictions

components/ResidentPage/CaseNoteDialog.tsx
https://trello.com/c/Dwn7mQiF/895-case-notes-arrows-get-stuck-on-non-case-notes
> this happens because workflows don't render a big chunk of the content inside the dialog, which is what the user was focused on. therefore focus is no longer "inside" the dialog when moving to a workflow, therefore the keyboard events aren't caught.
> we can prove this by clicking into the dialog of a workflow directly, or clicking on it after sliding into it with the keyboard. the arrows will then work again.
fixes it by moving the event listener off the dialog and onto the document element
=> fix: fix arrow nav

cypress/integration/team_allocations.ts
**What**  
This PR changes the worker that's used for e2e tests
**Why**  
The previous worker is not available anymore
=> fix: Changed worker for Allocations e2e tests

components/StopDialog.spec.tsx, components/StopDialog.tsx
**What**  
Small wording update to the message shown on children's records
**Why**  
This is so there's clearer messaging on the alert
=> fix: Update warning message on children records

components/ResidentPage/CaseNoteDialog.spec.tsx, components/ResidentPage/CaseNoteDialog.tsx
**What**  
Update the replace function to replace based on regex 
**Why**  
This ensures that all instances of special characters are replaced, rather than just the first instance
We've replaced the majority of special characters that we've seen but may need to do more in the future
=> fix: Fix case note tags

components/TeamPage/Layout.tsx, components/TeamPage/TeamAllocationsList/TeamAllocationsList.module.scss, components/TeamPage/TeamAllocationsList/TeamAllocationsList.spec.tsx, components/TeamPage/TeamAllocationsList/TeamAllocationsList.tsx, components/TeamPage/TeamWorkerList/TeamWorkerList.tsx, components/WorkerView/WorkerAllocations/WorkerAllocations.module.scss, components/WorkerView/WorkerAllocations/WorkerAllocations.spec.tsx, components/WorkerView/WorkerAllocations/WorkerAllocations.tsx
**What**  
- When an allocation is created the same day, the time difference was calculated from midnight. Now it displays "Today"
- The links now points to the allocation page, rather than the main resident
- Adjusted the text in Worker Allocation so it displays "Date allocated" instead of the redundant worker name
- Colour of small text is now  #585d60;
- Teams link is now always in non-visited state
- Added a bottom margin of 35px to the team name
- Added a top margin to the first element of the worker list
Now displays "today"
Displays "Date allocated" instead of the worker name in Worker Allocation view
Colour is now #585d60
Teams link is now always in non-visited state
Bottom margin of 35px to the team name
Added a top margin to the first element of the worker list
**Anything …
=> fix: Fixes for Worker and Team allocation

components/TeamPage/TeamAllocationsList/TeamAllocationsList.spec.tsx, components/TeamPage/TeamAllocationsList/TeamAllocationsList.tsx, components/TeamPage/TeamWorkerList/TeamWorkerList.spec.tsx, components/TeamPage/TeamWorkerList/TeamWorkerList.tsx, components/WorkerView/WorkerAllocations/WorkerAllocations.spec.tsx, components/WorkerView/WorkerAllocations/WorkerAllocations.tsx, types.ts
**What**  
This PR adds support for the parameter `teamAllocationStartDate`.
This parameter is still not sent by the backend
**Why**  
There's no current support for the Team Allocation start date
=> feat(SCT-1823): Added support for teamAllocationStartDate

data/forms/create-new-person.tsx
**What**  
Bringing "add new resident" page's Gender field into parity with the new Resident view
**Why**  
Because Trans and nonbinary people's lives matter
No tests as this was a small data change
=> chore: Gender Consolidation

lib/allocatedWorkers.spec.ts, lib/allocatedWorkers.ts, pages/api/residents/[id]/allocations/[allocationId].ts, pages/residents/[id]/activity.tsx, pagesTest/residents/[id]/activity.spec.tsx
**What**  
API changes:
-Adjust the FE to load the allocation by ID when loading a timeline allocation element
-Changes the status parameter sent  when showOnlyOpen is set to false from "closed" to undefined, as the meaning of the boolean is "load all" and not "load only the closed ones"
UI changes:
-Check nextCursor existence and hide the button in case it’s null
-Add a spinner when loading data
-Center the Load More button
**Why**  
The Activity list stopped working properly because of the new Allocation system.
The UI was also not behaving properly
- Have you added any new third-party libraries? X 
=> fix(SCT-1826): Activity list bugs/tweaks

components/AllocatedWorkers/AllocationRecap/AllocationRecap.tsx, components/AllocatedWorkers/AllocationRecap/__snapshots__/AllocationRecap.spec.tsx.snap
**What**  
Minor wording changes to the allocation recaps 
**Why**  
The allocation recaps was always saying 'Worker' even when there was a 'Team' allocation
- Have you added any new third-party libraries? X
=> fix: Reword allocation recaps

components/Layout/PhaseBanner/PhaseBanner.spec.tsx, components/Layout/PhaseBanner/PhaseBanner.tsx, components/Layout/PhaseBanner/__snapshots__/PhaseBanner.spec.tsx.snap, components/Layout/index.tsx
**What**  
Have updated the banner to link to the FAQ, handbook and support
**Why**  
These are the places where people should now be turning to for support
=> chore: Banner updated to add links to FAQ, Handbook and Support

components/ResidentPage/CustomGPDetailsEditor.tsx, components/ResidentPage/CustomKeyContactsEditor.tsx, components/ResidentPage/CustomPhoneNumberEditor.tsx, components/ResidentPage/InlineEditor.tsx
**What**  
This PR removes the usage of the hook `useClickOutside` on certain inputs on the resident details page.
**Why**  
This is to stop inputs on the page from closing if a user clicks anywhere outside the input. Now they will have to click the X icon to close the input.
=> chore: Remove ability to click out of an input

components/TeamPage/TeamWorkerList/TeamWorkerList.tsx
**What**  
This PR sorts by firstname/lastname the worker list in the team view
**Why**  
There was no ordering before
=> chore: Sorts the team worker list by firstname/lastname

components/TeamPage/TeamWorkerList/TeamWorkerList.spec.tsx, components/TeamPage/TeamWorkerList/TeamWorkerList.tsx
**What**  
While importing data, we set some of the dates to 01-01-0001 as they were required by the system.
This PR hides that date from the UI as it doesn't make sense to display it.
=> fix(SCT-1851): Don't display the date if it's the dummy imported one

components/ResidentPage/CaseNoteDialog.spec.tsx, components/ResidentPage/CaseNoteDialog.tsx
**What**  
This PR stops the keyboard navigation from opening the case notes dialog on the resident details by only updating the path to open a case note on the case-notes page on the resident view.
**Why**  
This is to stop users from being able to opening the case note dialog on any other page beside the case-notes page on the resident view.
Any suggestions to improve this would be helpful, I am not very knowledgeable on how events work.
=> chore: Stop opening of case-note dialog on resident details page

components/ResidentPage/CaseNoteDialog.spec.tsx, components/ResidentPage/CaseNoteDialog.tsx, components/ResidentPage/CaseNoteTile.spec.tsx, components/ResidentPage/CaseNoteTile.tsx, components/ResidentPage/WorkflowInfoBadge.module.scss, components/ResidentPage/WorkflowInfoBadge.spec.tsx, components/ResidentPage/WorkflowInfoBadge.tsx, hooks/useWorkflowIds.spec.tsx, hooks/useWorkflowIds.ts
**What**  
* Have added a new workflow information badge in to case note titles and case note dialog
* The information badge will only display information if the note is for a workflow and the workflow type is 'Review', 'Reassessment' or if it was not possible to get the workflow type
* A new hook has been made to enable this
* Additional tests have been written for this 
**Why**  
It was unclear to users when workflows were reviews or reassessments on the mainstream app, so this label was added to clarify this
We should check this once it's been deployed to staging to be sure that reviews, reassessments and assessments are all clear
=> feat: Workflow info labels

lib/appConfig.spec.tsx, lib/appConfig.tsx, zap-baseline.conf
**What**  
Only throw an `AppConfigProvider` error when getting a config value, rather than when calling `useAppConfig()`.
**Why**  
Errors are thrown when static pages are loaded, even though they never actually pull data from the `AppConfigProvider`.
=> fix: AppConfigProvider errors on static pages

components/GroupRecording/GroupRecordingWidget.spec.tsx, components/GroupRecording/GroupRecordingWidget.tsx, pages/people/[id]/case-note.tsx, pages/submissions/[id]/steps/[stepId].tsx
**What**  
This PR adds the XSRF-TOKEN for all the calls in Case Notes that don't use the standard API routes.
**Why**  
The offended rows were not implementing the token, so an error was returned
=> fix: Csrf token for Case Notes

lib/apiHandler.ts
**What**  
Fix 502 errors when not authenticated.
**Why**  
Api handler needs responses to be ended, otherwise they stay open and time out.
=> fix: end responses when unauthed

components/Layout/__snapshots__/index.spec.tsx.snap, components/Layout/index.tsx, components/ResidentPage/WorkflowTree.spec.tsx, components/SitewideAnnouncement/SitewideAnnouncement.tsx, stylesheets/all.scss
**What**  
Add site wide warning message asking users not to record anything in the application and advising them to view the intranet page for more information.
Also fix tests that were broken due to date time based checks.
**Why**  
ASC is migrating to Mosaic, so this application is no longer used as a recording tool
=> feat: Add site wide warning
