LBHackney-IT/lbh-social-care-frontend

SAMPLE.env, components/AdminLogin/AdminLogin.jsx, components/AdminNavBar/AdminNavBar.jsx, components/AdminNavBar/AdminNavBar.module.scss, components/Layout/index.jsx, lib/urls.js, next-seo.config.js, package.json, pages/_app.js, pages/_document.js, pages/access-denied.jsx, pages/index.js, pages/login.jsx, pages/logout.jsx, utils/auth.js, utils/urls.js, yarn.lock
New: 
- SAMPLE.ENV
- Next Seo Config file
- Admin Login Component
- Admin NavBar Component and scss
- Lib URLs
- Access Denied Page
- Login Page
- Logout Page
Updated:
- Layouts index page Header text
- Add Next SEO to _app.js
- _document.js
- Add authentication check and AdminNavBar to the home index page
=> Setup Google authentication

components/Cases/Cases.jsx, components/Cases/CasesTable.jsx, components/Cases/CasesTable.spec.jsx, components/Cases/__snapshots__/CasesTable.spec.jsx.snap, components/Layout/BackButton/BackButton.jsx, components/Search/ResultTable.jsx, components/Search/__snapshots__/ResultTable.spec.jsx.snap, pages/index.jsx, pages/people/[id]/cases.jsx, pages/people/search.jsx, stylesheets/all.scss, utils/api/cases.js
**What**  
Added people cases page
**Extras**
- Added back button component
- Added link to search in the homepage
- Added link search -> people cases
=> Person cases view

README.md
**What**  
This is need to spin up the application locally.
=> updated readme to include host file info

package.json
**What**  
Added `heroku` conf to `package.json`.
`$PORT` is going to be injected dynamically from heroku.
**How to test it in local?**
- `yarn build`
- run `PORT=1234 yarn start`
=> added heroku config

utils/auth.js
**What**  
Add logic to cater for the 2 new user groups for Adults and Children.
=> Update auth to cater for Adults and Childrens Google User groups

components/LinkButton/LinkButton.jsx, pages/index.jsx, pages/steps/case-notes-recording.jsx
**What**  
Link button component 
Basic dashboard
Code tidy 
**Why**  
Display forms
- Have you added any new third-party libraries? n/a
- Are any new environment variables or configuration values needed? n/a
- Anything else in this PR that isn't covered by the what/why? n/a
=> linkbutton, dashboard, tidy

components/Search/Search.jsx, pages/api/residents/index.js, utils/server/residents.js, utils/server/residents.spec.js
**What**  
Add load more for search results.
=> added load more on search results

components/Search/Search.jsx, utils/api/residents.js, utils/api/residents.spec.js, utils/server/residents.js, utils/server/residents.spec.js, utils/user.js, utils/user.spec.js
**What**  
Added the filter to the search based on user permissions.
- Overwrite the `user` permissions 👇 
https://github.com/LBHackney-IT/lbh-social-care/blob/develop/pages/_app.jsx#L27
```
-            user: this.props.userDetails,
+            user: {
+              ...this.props.userDetails,
+              hasAdminPermissions: false,
+              hasChildrenPermissions: false,
+              hasAdultPermissions: true,
+            },
```
- search for some children and see that they are not visible
=> passed filter for user permission to the residents APIs

public/robots.txt
**What**  
Added robot.txt to avoid search engines to index the website.
=> added robot.txt

components/Search/ResultTable.jsx, components/Search/Search.jsx, components/Search/__snapshots__/ResultTable.spec.jsx.snap
**What**  
- fixed spinner logic
- improved header appearance
=> Improved search result look&feel

package.json, pages/api/postcode/[postcode].js, pages/api/residents/[id]/cases.js, pages/api/residents/[id]/index.js, pages/api/residents/index.js, yarn.lock
**What**  
- Improved status codes (adding [`http-status-codes`](https://github.com/prettymuchbryce/http-status-codes))
- Improved postcode API (added auth check and `GET` handler)
=> improved status codes

components/Layout/PhaseBanner/PhaseBanner.jsx, components/Layout/index.jsx
=> add feedback form

components/DynamicStep/DynamicStep.jsx, components/FormWizard/FormWizard.jsx, components/Summary/Summary.jsx, components/Summary/Summary.stories.jsx, components/Summary/SummaryList.jsx, pages/form/adult-referral/[stepId].jsx
**What**  
- added summary step to the forms
- check the `adult-referral` form
- after the last step there will be the Summary
- the submission has to work as before
=> added summary step

components/Search/Search.jsx, components/Search/SearchForm.jsx, components/Search/SearchForm.spec.jsx, cypress/integration/search_admin_dev.js, pages/people/search.jsx
**What**  
- always use `GET /residents` of search
- removed OR logic in search
- added basic test for `SearchForm` component
=> always use /residents on search

components/Summary/Summary.jsx
**What**  
Fixed merge issues introduced by #50.
=> fixed summary merge

cypress.json
**What**  
Several times the first test is failing as the APIs are returning 500, hopefully, this is going to mitigate that problem.
=> added retries to cypress tests to avoid false positive

data/forms/child-referral.jsx
**What**  
Add conditional rendering for child FAST form so that it matches google form.
Some sections need to be reviewed by UX colleagues as the 'Consent' section for example it's unclear what should happen if the person says no to the first question.
=> add conditional redering

.circleci/config, .circleci/config.yml, lambda.js, next.config.js, package.json, serverless.yml
**What**  
This PR includes the addition of the serveless framework to allow us to set up all the infrastructure on our AWS environments to host the application. It also includes all the changes to the pipeline which allow us to deploy the code to staging and production
**Why**  
We have decided to move the hosting of the application to AWS as certain issues found from the pen test could not be solved if the application was continued to be held on Heroku
Once everything has been confirmed to be working, we must decommission the site on Heroku
- Anything …
=> Set up serverless to deploy lambda to AWS

components/DynamicStep/DynamicStep.jsx, components/Summary/Summary.jsx, utils/steps.jsx, utils/steps.spec.jsx
**What**  
Added conditional component.
Now it's possible to show components based on a condition (`conditionalRender`):
```
{
component: 'TextInput',
conditionalRender: ({ conditional_trigger }) =>
conditional_trigger === 'Yes',  
name: 'conditional_input',
rules: { required: true },
},
```
**Extras**
Improved `filterStepsOnCondition`, now it's returning all the valid step, making the condition easier to read.
=> conditionally render the component

components/Cases/CasesTable.jsx, components/Cases/CasesTable.spec.jsx, components/Search/results/CasesTable.jsx, components/Search/results/CasesTable.spec.jsx, components/Search/results/__snapshots__/CasesTable.spec.jsx.snap, utils/date.js, utils/date.spec.js
**What**  
- added `isValidDate` util
- added `formatDate` util
- added tests for date util
=> prevent to show invalid dates in case table

components/Search/Search.spec.jsx, components/Search/results/ResidentsTable.jsx, jest.config.js
=> added test for Search

pages/people/[id]/index.jsx
**What**  
Hide create new record button for later.
**Why**  
Production isn't ready
=> hide create new person and record

components/Search/Search.jsx, pages/api/cases/index.js, pages/api/residents/[id]/cases.js, pages/api/residents/[id]/index.js, pages/api/residents/index.js, pages/form/child-referral/[...stepId].jsx, pages/form/create-new-person/[...stepId].jsx, utils/api/cases.js, utils/api/cases.spec.js, utils/api/residents.js, utils/api/residents.spec.js, utils/server/cases.js, utils/server/cases.spec.js, utils/server/residents.js, utils/server/residents.spec.js
**What**  
- added addResident API
- improved existing API
- improved test coverage
**API now supported**:
```
GET /api/residents
GET /api/residents/:id
GET /api/residents/:id/cases
GET /api/cases
POST /api/cases
POST /api/residents
```
**Bonus**
- fixed alignment of the search result header
=> added addResident API

components/Layout/Header/Header.jsx, components/Search/forms/SearchCasesForm.jsx, components/Search/forms/SearchCasesForm.spec.jsx
**What**  
Label change to remove confusion over cases, records and notes
**Why**  
- Have you added any new third-party libraries? n/a
- Are any new environment variables or configuration values needed? n/a
- Anything else in this PR that isn't covered by the what/why? n/a
=> label change

components/PersonView/PersonDetails.jsx
**What**  
Filtered out the N and Y values in the address table 
**Why**  
=>  N and Y values address fix

components/PersonView/PersonDetails.jsx, components/PersonView/PersonDetails.spec.jsx, components/PersonView/__snapshots__/PersonDetails.spec.jsx.snap
**What**  
As requested by business used `displayAddressFlag` instead of `contactAddressFlag`.
Plus added a snapshot test, testing the generate DOM and the expand functionality.
=> show display address

components/LinkButton/LinkButton.jsx, pages/people/[id]/record.jsx
**What**  
Quick fix to link button 
**Why**  
=> link button fix

components/DynamicStep/DynamicInput.jsx, components/Form/AddressLookup/AddressLookup.jsx, components/Steps/Confirmation.jsx, components/Summary/Summary.jsx, pages/api/postcode/[postcode].js, utils/postcodeAPI.js, utils/postcodeAPI.spec.js, utils/server/postcode.js, utils/server/postcode.spec.js
**What**  
- Improved postcode API
- Updated postcode API to the latest version
- Improved the AddressLookup component (in manual mode only ask for **address** and **postcode**)
`AddressLookup` now it's a properly controlled form element and not a hybrid as before.
The easiest way is using storybook 🚀
=> updated and improved postcode api and AddressLookup

components/Layout/Header/Header.jsx, components/Search/Search.jsx, pages/_app.jsx, pages/cases/index.jsx, utils/saveData.js
**What**  
In progress fix and search label fix 
**Why**  
=> in progress fix

components/FormCasesWrapper/FormCasesWrapper.jsx, components/FormWizard/FormWizard.jsx, components/SaveFormData/SaveFormData.jsx
**What**  
Save functionality query string.
**Why**  
All form will now have query strings
=> query string on save

components/PersonView/PersonDetails.jsx
**What**  
If the APIs returns `null` the date of birth is formatted as `01/01/1970 `.
Now we are only showing the fields if the correspondent value is present.
=> only show fields if they exist

.circleci/config.yml
**What**
The artifacts generation is currently broken, making debugging E2E errors difficult.
=> fixed artifacts generations on e2e

components/Cases/Cases.jsx, components/PersonView/PersonView.jsx, components/Spinner/Spinner.jsx, pages/api/residents/[id]/cases.js, pages/people/[id]/index.jsx, utils/api/cases.js, utils/api/cases.spec.js, utils/server/cases.js, utils/server/cases.spec.js
**What**  
- moved cases header inside its component
- added load more to the cases
- improved the spinner (made it centred)
- fixed spinner per person view
=> Added load more in cases for person view

.circleci/config.yml
Reverts LBHackney-IT/lbh-social-care#96 as it's breaking push to staging.
=> Revert "fixed artifacts generations on e2e"

.circleci/config.yml
**What**  
- Fixed append of artifacts in circleci 
- broke down `install-dependencies-tests` step in `install`, `tests`, `e2e`
- fixed required steps in the CI flow
=> fixed path of artifacts

components/PersonView/PersonDetails.jsx, components/PersonView/__snapshots__/PersonDetails.spec.jsx.snap
=> expose all available phone numbers

components/SaveFormData/Tables.jsx, components/Search/results/ResidentsTable.jsx
**What**  
Only format the date if exist.
`new Date(null).toLocaleDateString('en-GB')` is returning `01/01/1970`, preventing this to happen.
=> only format the date if exist

components/Form/DateInput/DateInput.jsx, components/Search/forms/SearchCasesForm.jsx, components/Summary/Summary.jsx, utils/date.js, utils/date.spec.js
**What**  
- fixed date validation on `DateInput` with EU format
- created `coverFormat` in `utils/date`
- added `converFormat` to the `Summary`
=> fixed validation on EU format

components/Cases/CasesTable.jsx, components/Cases/__snapshots__/CasesTable.spec.jsx.snap, components/Search/results/CasesTable.jsx, components/Search/results/__snapshots__/CasesTable.spec.jsx.snap, data/forms/child-referral.jsx
**What**  
Used proper anchor + href rather than `onCLick`
**Plus**
Added `rel=noopener` to the external links
=> refactored link to use href rather than onClick

components/Form/Checkbox/Checkbox.jsx, components/Form/DatePicker/DatePicker.jsx, components/Form/Radios/Radios.jsx, utils/steps.jsx, utils/steps.spec.jsx
**What**  
Forms with `isMulti` step were breaking on `Summary`.
=> fixed filterDataOnCondition when step isMulti

components/Search/Search.jsx, pages/api/cases/index.js, pages/api/residents/[id]/allocated-workers.js, pages/api/residents/[id]/cases.js, pages/api/residents/[id]/index.js, pages/api/residents/index.js, utils/server/allocatedWorkers.js
**What**  
Moved `context_flag` logic into the BE layer.
- added context_flag to get requests (residents, cases, allocated_workers)
- removed context_flag from Search component
=> added context_flag to all the get requests

components/Layout/Header/Header.jsx, components/Layout/index.jsx, utils/user.js, utils/user.spec.js
**What**  
Added type of the user in the header, along with the service name.
=> added user type in the header

components/AllocatedWorkers/AllocatedWorkersTable.jsx, components/AllocatedWorkers/__snapshots__/AllocatedWorkersTable.spec.jsx.snap
**What**  
Add end date back onto allocated worker entry component
=> Add end date back onto allocated worker entry

cypress/integration/form.js, cypress/integration/search_admin_dev.js, cypress/integration/search_by_name_adult_admin.js, cypress/integration/search_by_name_children_admin.js, package.json, pages/form/test/[...stepId].jsx, yarn.lock
**What**  
Added basic test for test form, testing:
- step conditional rendering
- input condition rendiering
- multi step
- urls
- submission
**Plus**
- Refactored existing E2E tests
- Updated Cypress to the latest version
=> added basic E2E tests for form test

fixture/allocatedTestData.js
**What**  
Test data for allocated workers. 
**Why**  
We're ahead of the backend and need test data to populate components 
=> allocated workers test data

components/AdminLogin/AdminLogin.spec.jsx, components/AdminLogin/__snapshots__/AdminLogin.spec.jsx.snap, components/Cases/Cases.spec.jsx, components/Cases/__snapshots__/Cases.spec.jsx.snap, components/DynamicStep/DynamicStep.spec.jsx, components/DynamicStep/__snapshots__/DynamicStep.spec.jsx.snap, components/ErrorSummary/ErrorSummary.spec.jsx, components/ErrorSummary/__snapshots__/ErrorSummary.spec.jsx.snap, components/Form/Select/Nationality.jsx, components/Form/Select/Nationality.spec.jsx, components/Form/Select/Select.jsx, components/Form/Select/Select.spec.jsx, components/Form/TextArea/TextArea.spec.jsx, components/Layout/Header/Header.spec.jsx, components/Layout/index.spec.jsx, components/LinkButton/LinkButton.spec.jsx, components/LinkButton/__snapshots__/LinkButton.spec.jsx.snap, components/PersonView/PersonView.spec.jsx, components/SaveFormData/SaveFormData.jsx, components/SaveFormData/SaveFormData.spec.jsx, components/SaveFormData/Tables.jsx, components/SaveFormData/Tables.spec.jsx, components/SaveFormData/__snapshots__/SaveFormData.spec.jsx.snap, components/SaveFormData/__snapshots__/Tables.spec.jsx.snap, components/Steps/Confirmation.spec.jsx, components/Steps/Summary.spec.jsx, components/Steps/__snapshots__/Confirmation.spec.jsx.snap, components/Steps/__snapshots__/Summary.spec.jsx.snap
**What**  
Update to code coverage. 
**Why**  
Code coverage was around 50% and now it's 73.%. There's two files that currently can't be tested due to their implementation. 
=> unit tests

components/AddForm/AddForm.jsx, components/AddForm/AddForm.spec.jsx, components/AddForm/__snapshots__/AddForm.spec.jsx.snap, components/Cases/Cases.jsx, components/Form/Select/Select.jsx, data/googleForms/adultCategories.js, data/googleForms/adultForms.js, data/googleForms/childCategories.js, data/googleForms/childForms.js, pages/people/[id]/records.jsx, utils/populate.jsx
**What**  
To test please change the cookie to children but note that the full name is "Admin Children" in the user. So it will populate that username in the forms. To see your name change getUserType(user) === 'Children' to getUserType(user) === 'Admin'
**Why**  
=> google forms

components/AddForm/AddForm.spec.jsx, data/googleForms/adultCategories.js, data/googleForms/adultForms.js
**What**  
Update to Joy's categories
=> Category update

stylesheets/all.scss
**What**  
Requested style change to links.
=> link colour update

components/AddForm/AddForm.jsx, components/AddForm/AddForm.spec.jsx, components/AddForm/__snapshots__/AddForm.spec.jsx.snap
**What**  
- fixed warning on tests
- only show **load form** if the URL is selected, preventing redirect to 404 if the form is not selected
=> improve load form and fixed warning in tests

components/Cases/Cases.jsx
=> removed admin flag from the add records

data/googleForms/adultForms.js
Additional google form was created, adding to the rest.
=> additional form

data/forms/create-new-person.jsx, data/religions.js
=> added religion select

components/Form/Select/Select.jsx, components/Form/Select/Select.stories.jsx
=> added a custom placeholder if select is required

data/ethnicities.js, data/forms/create-new-person.jsx
=> add ethnicities and sub-ethnicities to add new person

components/AllocatedCases/AllocatedCases.jsx, components/AllocatedCases/AllocatedCasesTable.jsx, components/AllocatedCases/__snapshots__/AllocatedCasesTable.spec.jsx.snap
**What**  
Gill request: remove assessment type and update no allocations message
=> product review changes

components/FormWizard/DynamicInput.jsx, data/forms/create-new-person.jsx, data/forms/test.jsx
**What**  
It's not mandatory adding the **conditional render** on options as a function
=> Improved selects/radios with `options` as `function`

components/FormWizard/DynamicStep.jsx, cypress/integration/form.js, data/forms/test.jsx, docs/formBuilder/02-FormSteps.stories.mdx
**What**  
- added E2E test covering the functionality
- updated documentation
- fixed `child-referral` form
=> fixed rendering of nodes in component lists

components/PersonView/PersonDetails.jsx
Add person type to inform users if the person is a child or adult
=> person type

pages/api/cases/index.js, pages/api/postcode/[postcode].js, pages/api/residents/[id]/allocated-workers.js, pages/api/residents/[id]/cases.js, pages/api/residents/[id]/index.js, pages/api/residents/index.js, pages/api/teams/[team_id]/workers.js, pages/api/teams/index.js, pages/api/workers/[id]/allocations.js
**What**  
At the moment is possible to access the APIs if only a valid hackneyToken is present
**How to test it?**
- Check the APIs as `unauthenticate` user
- Check the APIs as `authenticate` user but not part of the correct group
=> fixed auth in api

components/Form/Checkbox/Checkbox.jsx, components/Form/DateInput/DateInput.jsx, components/Form/DatePicker/DatePicker.jsx, components/Form/PhoneInput/PhoneInput.jsx, components/Form/Radios/Radios.jsx, components/Form/Select/Select.jsx, components/Form/TextArea/TextArea.jsx, components/Form/TextInput/TextInput.jsx, components/FormWizard/DynamicInput.jsx, components/FormWizard/DynamicStep.jsx
Fixed validation on inputs by using register as a function with the rules. The definition of register with rules has been moved from the Dynamic Input to the single components.  
https://trello.com/c/cLxzEZlh/687-phone-input-bug
=> don't allow phone input to accept letters

serverless.yml
add provisioned concurrency for lambda latency issue
=> add provisioned concurrency for lambda latency issue

components/Steps/Summary.jsx, utils/objects.js, utils/objects.spec.js
**What**
- added sanitiseObject util
- sanitised data on submit
- go to create new person form
- fill a new form leaving email empty
- the form submission should succed
=> sanitised data before formWizard submit

components/Form/AddressLookup/AddressLookup.jsx, components/FormWizard/FormWizard.jsx, components/Search/Search.jsx, components/Steps/PersonConfirmation.jsx, components/Steps/PersonConfirmation.spec.jsx, components/Steps/Summary.jsx, components/Steps/__snapshots__/PersonConfirmation.spec.jsx.snap, pages/form/create-new-person/[...stepId].jsx, utils/steps.jsx, utils/steps.spec.jsx
Confirmation page for create new person
Joy asked us to remove the confirmation message and Felix requested the ID be on the page
=> confirmation page for new person

components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.jsx, components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.spec.jsx, components/AllocatedWorkers/DeallocateWorker/DeallocateWorker.jsx, pages/api/residents/[id]/allocated-workers.js, utils/server/allocatedWorkers.js, utils/server/allocatedWorkers.spec.js
- aligned allocations to the new API
- replace the delete allocation url (so the browser back button doesn't show an already deleted allocation)XX
=> aligned allocations api to BE

components/Button/Button.jsx, components/FormWizard/DynamicStep.jsx, components/FormWizard/DynamicStep.spec.jsx, components/FormWizard/__snapshots__/DynamicStep.spec.jsx.snap, components/PersonView/PersonDetails.jsx, components/PersonView/__snapshots__/PersonDetails.spec.jsx.snap, components/Steps/PersonConfirmation.jsx, components/Steps/Summary.jsx, components/Steps/Summary.spec.jsx, components/Steps/__snapshots__/Confirmation.spec.jsx.snap, components/Steps/__snapshots__/PersonConfirmation.spec.jsx.snap, components/Steps/__snapshots__/Summary.spec.jsx.snap, components/Summary/Summary.jsx, components/Summary/__snapshots__/Summary.spec.jsx.snap, cypress/integration/form.js, data/forms/create-new-person.jsx
=>  design update

components/FormWizard/FormWizard.jsx, components/Steps/PersonConfirmation.jsx, components/Steps/__snapshots__/PersonConfirmation.spec.jsx.snap
=> design changes

components/Cases/Cases.jsx, components/Cases/Cases.spec.jsx, components/Cases/__snapshots__/Cases.spec.jsx.snap
**What**  
If the person is restricted, along with showing the error, it shouldn't call the APIs.
=> don't call the APIs if restricted

components/FormCasesWrapper/FormCasesWrapper.jsx, components/FormWizard/DynamicInput.jsx, components/FormWizard/FormWizard.jsx
- cached personId and added missing component
- extended `FormWrapper` for hide the back button
- prevent error on console for unsupported prop
=> fixed formCaseWrapper

components/FormWizard/DynamicStep.jsx, components/Steps/Summary.jsx
**What**  
Added browser warning on form cancel
=> ask if you want to proceed on cancel

components/Search/Search.jsx, components/Search/Search.spec.jsx
**What**  
Prevento scroll to top on new search.
=> don't scroll to page top on search

components/PersonView/PersonDetails.jsx, components/PersonView/PersonDetails.spec.jsx, components/PersonView/PersonView.spec.jsx, components/PersonView/__snapshots__/PersonDetails.spec.jsx.snap
not able to be tested until we get the api data
=> update person view to reflect data collected

components/Search/results/CasesTable.jsx, components/Search/results/CasesTable.spec.jsx
**What**  
fallback to `createDateTimestamp` if `dateOfEvent` does not exist
=> fallback to timestamp if date of event does not exist

components/AddForm/AddForm.jsx
Show no placeholder if there is only one form.
=> display one form if only one exists

components/AllocatedWorkers/AllocatedWorkersTable.jsx, components/AllocatedWorkers/__snapshots__/AllocatedWorkersTable.spec.jsx.snap
=> fixed casing in allocation table

components/AllocatedWorkers/AllocatedWorkersTable.jsx, components/AllocatedWorkers/__snapshots__/AllocatedWorkersTable.spec.jsx.snap
**What**  
Fixed casing in allocation titles
=> Fixed casing in Allocation titles

components/AllocatedWorkers/AllocatedWorkers.jsx
**What**  
`hasAllocatorGroup` will only be used to show and hide the buttons, not the whole optional box
=> show allocation box even if not in the allocation group

components/Search/forms/SearchCasesForm.jsx
=> changed worker filter to uploaded by

utils/forms.spec.ts, utils/forms.ts, utils/user.ts
=> converted utils/forms to TS

pages/people/[id]/case-notes-recording/[[...stepId]].tsx, utils/server/cases.spec.ts, utils/server/cases.ts
**What**  
Aligned cases POST to the following structure expected by the BE:
```
{
"personId": 234,
"firstName": "First",
"lastName": "Last",
"contextFlag": "A",
"workerEmail": "first.last@domain.com",
"formName": "ASC form name",
"formNameOverall": "ASC form name overall",
"dateOfBirth": "18/12/1960",
"caseFormData": "{\"custom_prop_1\":\"Additional Hours Requested\", \"custom_prop_2\":\"i am a title\",\"custom_prop_3\":\"i am a description\"}"
}
```
- go to `/people/234/case-notes-recording`
- add a note
- it should work as expected
=> aligned case note post to BE

components/Search/Search.jsx, pages/people/add/[[...stepId]].tsx
**What**  
Only show "add new people" to adults or admins.
=> only show add new person for adults

components/AddForm/AddForm.jsx, components/AddForm/__snapshots__/AddForm.spec.jsx.snap, components/Form/Autocomplete/Autocomplete.jsx
=> more design

serverless.yml
**What**  
Has the BE API are returning timeouts quite often, let's try to avoind this increasing our default timeout.
=> increased lambda timeout to 10

components/Form/TextArea/TextArea.tsx
=> added required star if TextArea is required

components/Form/DatePicker/DatePicker.tsx, utils/summary.jsx
**What**
- format date to EU format in summary
- set default width to 10
=> date picker date format

components/Cases/CasesTable.jsx, components/Cases/__snapshots__/Cases.spec.jsx.snap, components/Search/results/CasesTable.jsx
Reverts LBHackney-IT/lbh-social-care#233
=> Revert "hide caseFormTimestamp from cases"

components/Cases/CaseLink.jsx, components/Cases/CaseRecap/CaseRecap.jsx, components/Cases/CaseRecap/CaseRecap.spec.jsx, components/Cases/CaseRecap/__snapshots__/CaseRecap.spec.jsx.snap, data/forms/index.jsx, pages/people/[id]/records/[recordId]/index.tsx
Updated form view
To test /44000000/records/6039265d832298cc73518c42
or create a case note and view it.
Please note old case notes are not visible as they don't have a form_name_overall which is require in caseLink to redirect you to the view form page
=> updated form view 

pages/people/[id]/allocations/[allocationId]/remove.tsx, pages/people/[id]/allocations/add.tsx, pages/people/[id]/index.tsx, pages/people/[id]/records/index.tsx, pages/workers/[id]/index.tsx
tiny PR updating titles on pages.
=> change titles on pages

components/AllocatedWorkers/AllocatedWorkers.jsx, components/Cases/Cases.jsx, components/Cases/__snapshots__/Cases.spec.jsx.snap, components/Layout/__snapshots__/index.spec.tsx.snap, components/Layout/index.tsx, components/PersonView/PersonDetails.tsx, components/PersonView/__snapshots__/PersonDetails.spec.tsx.snap, components/Stack/Stack.spec.tsx, components/Stack/Stack.stories.tsx, components/Stack/Stack.tsx, components/Stack/__snapshots__/Stack.spec.tsx.snap, components/WarningNote/WarningNotes.module.scss, components/WarningNote/WarningNotes.tsx, components/WarningNote/__snapshots__/WarningNotes.spec.tsx.snap, pages/login.tsx, pages/people/[id]/index.tsx, stylesheets/all.scss
**What**  
- Fixed spacing on person view page (inspired by https://mxstbr.com/thoughts/margin/)
- Removed all the margins from the components used in the page
- Added `Stack` component 
- Fixed table header styling
- Improved semantic of the `WarningNotes` component
- Removed unused classes from the layout
- Removed pointless prop-types in ts files
**Before**:
**After:**
Go to a person page and check that everything looks good
=> Fixed spacing on Person view page

components/WarningNote/WarningNotes.fixtures.ts, components/WarningNote/WarningNotes.spec.tsx, components/WarningNote/WarningNotes.stories.tsx, components/WarningNote/WarningNotes.tsx, components/WarningNote/__snapshots__/WarningNotes.spec.tsx.snap, lib/warningNotes.ts, pages/api/warning-notes/[warningNoteId].ts, types.ts
**What**
- Updated Warning note mocks
- Improved types for WarningNotes
- added `/api/warning-notes/:warningNoteId` endpoint
- check the new endpoint `http://dev.hackney.gov.uk:3000/api/warning-notes/123`
=> Improved Warning note mocked and updated types

data/forms/warning-note.tsx
**What**  
Added external links and improved layout.
=> added external links

components/Form/types.ts, components/FormWizard/DynamicStep.jsx, components/FormWizard/DynamicStep.module.scss, components/FormWizard/__snapshots__/DynamicStep.spec.jsx.snap, data/forms/warning-note.tsx
**What**  
- go to `http://dev.hackney.gov.uk:3000/people/234/warning-notes/add`
- check the question `Is the individual aware of the Warning Note and Review Date?`
- check that everything looks fine
=> added conditional rendering guides

pages/people/[id]/case-notes-recording/[[...stepId]].tsx
**What**  
The BE is expecting a number as personId
=> fix add new case

components/Search/results/CasesTable.jsx
View link is now displaying on search by records. 
http://dev.hackney.gov.uk:3000/cases?first_name=john
=> add view case link to record search

components/Cases/CaseRecap/CaseRecap.spec.tsx, components/Cases/CaseRecap/__snapshots__/CaseRecap.spec.tsx.snap, components/Cases/CasesTable.spec.tsx, components/Cases/CasesTable.tsx, components/Cases/__snapshots__/Cases.spec.tsx.snap, components/Cases/__snapshots__/CasesTable.spec.tsx.snap, fixtures/cases.fixtures.ts
**What**  
- improved UI of the table
- added title and case note prefix on the records
**before:**
**after:**
=> improved ui of the table

components/Layout/Seo/Seo.tsx, components/Layout/Seo/__snapshots__/Seo.spec.tsx.snap, components/Layout/index.tsx
**What**  
We removed the "interim" word from the project 💥
=> banned "interim" word from the codebase

components/Search/Search.jsx, data/forms/create-new-person.tsx
**What**
- made address lookup non-mandatory
- show create new person to allocators
=> enabled create new person for allocators

utils/date.spec.ts, utils/date.ts
=> extended stringDateToObject to support ISO string format

data/forms/create-new-person.tsx
=> made the date of birth not mandatory

data/forms/asc-referral.tsx, pages/people/[id]/records/referral/[[...stepId]].tsx
Note: the second step has a condition that ends the form if you state "Was information and advice offered?" = no. For this reason I've moved the rest of the questions to the final step
To test
Form conditions:
Was information and advice offered? = yes 
Will this Contact lead to a Safeguarding Concern? = yes
Proceed to further case activities (provide details below) 
No Further Action
Designs
https://www.sketch.com/s/654c1c53-d967-4269-9507-25ca8423e730/a/pjwE0p
https://www.sketch.com/s/654c1c53-d967-4269-9507-25ca8423e730/a/VlbRyw
https://www.sketch.com/s/654c1c53-d967-4269-9507-25ca8423e730/a/gpybLr
Google form 
https://docs.google.com/forms/d/e/1FAIpQLSc4y4yjw6DpwWHN2fias1SEDo0lZZZNgN3M20Zy_p2He1rSuw/viewform
=> referral-update

components/AllocatedCases/AllocatedCases.spec.tsx, components/AllocatedCases/MyAllocatedCases.spec.tsx, components/AllocatedCases/MyAllocatedCases.tsx, components/AllocatedCases/__snapshots__/AllocatedCases.spec.tsx.snap, components/AllocatedCases/__snapshots__/MyAllocatedCases.spec.tsx.snap, components/Dashboard/DashboardWrapper.tsx, components/Dashboard/__snapshots__/DashboardWrapper.spec.tsx.snap, components/SaveFormData/SaveFormData.spec.tsx, components/SaveFormData/SaveFormData.tsx, components/SaveFormData/__snapshots__/SaveFormData.spec.tsx.snap, factories/workers.ts, lib/workers.spec.ts, lib/workers.ts, pages/api/me/index.ts, pages/my-allocations.tsx, utils/api/allocatedWorkers.spec.ts, utils/api/allocatedWorkers.ts, utils/api/cases.ts, utils/api/residents.ts, utils/api/warningNotes.ts
**What**  
- added myallocation tab to dashboard
- added `/api/me` to get worker information + allocations
- fixed deprecated interface `responseInterface` to `SWRResponse`
=> Added "my allocations" tab to the Dashboard

components/Cases/CaseLink.tsx, components/Cases/CaseRecap/HistoricNote.spec.tsx, components/Cases/CaseRecap/HistoricNote.tsx, components/Cases/CaseRecap/HistoricVisit.spec.tsx, components/Cases/CaseRecap/HistoricVisit.tsx, components/Cases/CaseRecap/__snapshots__/HistoricVisit.spec.tsx.snap, fixtures/cases.fixtures.ts, lib/cases.spec.ts, lib/cases.ts, pages/api/cases/historic-note/[caseId].ts, pages/api/cases/historic-visit/[caseId].ts, pages/people/[id]/visits/[recordId].tsx, types.ts, utils/api/cases.ts
**What**  
Added UI for the historic visit
- go to http://dev.hackney.gov.uk:3000/people/33339579
- check that the historic view and the historic case notes are working properly
=> added historic visit view

components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.spec.tsx, components/AllocatedWorkers/AddAllocatedWorker/AddAllocatedWorker.tsx, components/AllocatedWorkers/AddAllocatedWorker/__snapshots__/AddAllocatedWorker.spec.tsx.snap, components/AllocatedWorkers/DeallocateWorker/DeallocateWorker.tsx, lib/allocatedWorkers.spec.ts, lib/allocatedWorkers.ts, pages/people/[id]/allocations/[allocationId]/remove.tsx
**What**  
- added start date to add allocation
- added deallocation date to remove allocation
- fixed types for `deleteAllocatedWorker`
⚠️ Don't merge as it's blocked by the BE
=> add dates to add and remove allocation

components/AllocatedCases/AllocatedCases.tsx, components/AllocatedCases/AllocatedCasesTable.tsx, components/AllocatedCases/__snapshots__/AllocatedCasesTable.spec.tsx.snap, components/WorkerView/WorkerRecap.tsx, components/WorkerView/WorkerSearch.spec.tsx, components/WorkerView/WorkerSearch.tsx, components/WorkerView/__snapshots__/WorkerSearch.spec.tsx.snap, factories/APIerrors.ts, pages/_app.tsx, pages/api/workers/index.ts, pages/workers/index.tsx, types.ts, utils/api/workers.ts
Added functionality for searching workers in the system using their email. This page should display the workers details through the WorkerRecap Component and reuse the allocations functionality to display their allocations.
=> Manage worker

components/AddForm/AddForm.spec.tsx, components/AddForm/AddForm.tsx, data/googleForms/adultForms.ts, pages/people/[id]/records/case-notes-recording/[[...stepId]].tsx
**What**
- moved case-notes-recording
- used internal case notes recording
- go to `http://dev.hackney.gov.uk:3000/people/7/records`
- select **case notes recording**
- you should see the internal form
- fill the form
- it should work properly
=> add case note recording

components/Search/Search.jsx, components/Search/Search.spec.jsx, utils/auth.ts
**What**  
- _everyone_ can _add a new person_
- if you are either part of _allocators_ or _children_ groups you will be able to _allocate_
=> enable cfs users to allocate and create persons

components/Steps/PersonConfirmation.tsx, components/Steps/__snapshots__/PersonConfirmation.spec.tsx.snap
**What**  
Remove referral link and update confirmation page
=> update confirmation page

data/forms/create-new-person.tsx
**What**  
Restricted field for the backend for update person
=> Add restricted field

components/Form/DateInput/DateInput.tsx, components/Form/types.ts, utils/date.ts
**What**  
ISO format was wrongly named US format.
=> renamed date format to ISO

components/AllocatedWorkers/DeallocateWorker/DeallocateWorker.tsx, components/Cases/CasesTable.tsx, components/Cases/__snapshots__/Cases.spec.tsx.snap, components/Cases/__snapshots__/CasesTable.spec.tsx.snap, components/FormWizard/DynamicInputMulti.jsx, components/FormWizard/DynamicStep.jsx, components/FormWizard/__snapshots__/DynamicInputMulti.spec.jsx.snap, components/Layout/BackButton/BackButton.spec.tsx, components/Layout/BackButton/BackButton.tsx, components/Layout/BackButton/__snapshots__/BackButton.spec.tsx.snap, components/Search/Search.jsx, components/Search/forms/SearchCasesForm.tsx, components/Search/forms/SearchResidentsForm.tsx, components/WarningNote/WarningNotes.tsx, components/WarningNote/__snapshots__/WarningNotes.spec.tsx.snap, cypress/integration/form.ts, data/forms/create-new-person.tsx, data/forms/create-new-worker.tsx, pages/_document.tsx, pages/cases/index.tsx, pages/people/add/[[...stepId]].tsx, pages/workers/[id]/index.tsx
**What**  
Changes requested by accessibility audit.  
https://docs.google.com/document/d/12Xb7e9t_ILLMgM5WAy8XRzw4l-zEpizKm2dzpg0v6d0/edit#heading=h.pmt0n0x2n0d0
Left to do: 
Fix broken arias on Auto Complete
=> Accessibility changes

components/PersonView/PersonDetails.tsx, components/PersonView/__snapshots__/PersonDetails.spec.tsx.snap, components/Search/Search.jsx, components/Search/forms/SearchResidentsForm.tsx, components/ShowMoreBox/ShowMoreBox.tsx, components/ShowMoreBox/__snapshots__/ShowMoreBox.spec.tsx.snap, components/Summary/Summary.jsx, components/Summary/Summary.module.scss, components/Summary/__snapshots__/Summary.spec.jsx.snap, stylesheets/all.scss
**What**
- fixed styling for the button links
- converted more buttons
- removed superfluous attr
=> improved button links

components/Form/Checkbox/Checkbox.tsx, components/Form/Checkbox/__snapshots__/Checkbox.spec.tsx.snap, components/Form/TextArea/TextArea.tsx, components/FormWizard/FormWizard.jsx
**What**  
- fixed `aria` attr on `TextArea`
- fixed `aria` attr on `FormWizard` `fieldset`
- fixed `MultiCheckbox` attributes
**How to test it** 
- http://dev.hackney.gov.uk:3000/form/test/first-step
- click `bar` on _This is a multi checkbox_ and it should select the correct checkbox
=> fixed aria attr on textArea

lib/warningNotes.ts
=> use the real warning not get

components/Form/ObjectInput/ObjectInput.module.scss, components/FormWizard/DynamicInputMulti.module.scss
=> fixed dynamic multi object input

components/Layout/Header/Header.tsx, components/Layout/Header/__snapshots__/Header.spec.tsx.snap, components/WorkerView/WorkerSearch.tsx, data/forms/create-new-worker.tsx, lib/workers.ts, pages/api/workers/[id]/index.ts, pages/api/workers/index.ts, pages/workers/[id]/edit/[[...stepId]].tsx, pages/workers/add/[[...stepId]].tsx, pages/workers/index.tsx, utils/api/workers.ts
**What**  
- added `useWorkerById` functionality
- plugged `POST /workers`
- added `PATCH /workers`
- added **manage workers** into the nav section (only for `dev` users)
- added internal API for:
- `GET /workers/:id`
- `PATCH /workers/:id`
- `POST /workers`
**TODO**
Improve test coverage
- check add worker is working properly
- check update worker is calling the correct API
=> Wired up the BE for workers

README.md
=> small tweak to readme

components/Search/forms/SearchCasesForm.tsx, components/Search/forms/SearchResidentsForm.tsx
**What**  
Clear search was logging out the users
=> fixed clear search

components/Form/Autocomplete/Autocomplete.tsx
**What**  
If the `options` passed to the `Autocomplete` change the selection is not cleared, this PR is fixing that problem.
Needed by #335.
=> reset the selected value if the options change

pages/people/[id]/index.tsx
**What**  
Enable edit person to `admins` and `adults`, `children` will be deployed separately.
=> enable edit person to adults and admins

components/Cases/CaseLink.spec.tsx, components/Cases/CaseLink.tsx, components/Cases/__snapshots__/Cases.spec.tsx.snap, components/Cases/__snapshots__/CasesTable.spec.tsx.snap
this adds the proper classes to the "view" link on the records table
=> fix "view" link on records table

components/Form/PhoneInput/PhoneInput.spec.tsx, components/Form/PhoneInput/PhoneInput.tsx
Changed the RegExp so it doesn't let the user input a number with spaces + tests
=> SCT-196  Phone number validation blocking users from creating people

components/Layout/Header/Header.spec.tsx, components/Layout/Header/Header.tsx, components/Layout/Header/__snapshots__/Header.spec.tsx.snap, pages/index.tsx
conceals the existence of the dashboard until we want to use it.
=> redirect from dashboard and hide it from the menu

data/forms/edit-worker.tsx, pages/workers/[id]/edit/[[...stepId]].tsx
**What**  
[Ticket](https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=59&modal=detail&selectedIssue=SCT-217)
**Why**  
While updating a worker the email is passed to the back end which is not needed
=> Chore(SCT-217): Create edit worker form

components/Form/Radios/Radios.tsx
Tiny pr to straighten up labels with their radio buttons.
=> fix alignment of radio buttons

components/AddForm/AddForm.tsx, components/Cases/CaseLink.tsx, data/forms/index.tsx, data/googleForms/adultForms.ts
Change link from internal conv 3 form to google form.
=> remove conv 3

components/PersonView/PersonView.spec.tsx, lib/permissions.spec.ts, lib/permissions.ts
**What**  
Feature is not signed off for children workers yet so needs to be removed quickly.
=> fix(SCT-235): hotfix remove edit person from children workers

cypress/integration/search_for_person.ts, pages/api/residents/index.ts
**What**  
The updated search results wasn't approved, this reverts it!
=> fix: revert showing all records in search results

components/PersonView/PersonView.spec.tsx, lib/permissions.spec.ts, lib/permissions.ts
Reverts LBHackney-IT/lbh-social-care-frontend#375
=> Revert "fix(SCT-235): hotfix remove edit person from children workers"

pages/people/[id]/edit/[[...stepId]].tsx
Bug fix that makes sure that the "restricted" parameter is in the form data
=> SCT-223  Unable to edit people if you don't have admin permissions

cypress/integration/search_for_person.ts, pages/api/residents/index.ts
Reverts LBHackney-IT/lbh-social-care-frontend#376
This restores the "Show all records in search" feature that was taken out of yesterday's release.
=> Revert "fix: revert showing all records in search results"

cypress/integration/search_for_person.ts, pages/api/residents/index.ts
Triple revert, but don't worry, this is the git way 😌 .
**Check with Felix if this should be merged or not!**
Reverts LBHackney-IT/lbh-social-care-frontend#383
=> revert: "showing all records in search results"

components/ExpandDetails/ExpandDetails.spec.tsx, components/ExpandDetails/ExpandDetails.tsx, components/ExpandDetails/__snapshots__/ExpandDetails.spec.tsx.snap, components/PersonView/PersonDetails.tsx, components/PersonView/PersonView.spec.tsx, components/PersonView/__snapshots__/PersonDetails.spec.tsx.snap, cypress/integration/add_record.ts, cypress/integration/view_warning_note_details.ts, data/forms/warning-note.tsx
**What**  
Warning Note form structure changes for CFS.
**Why**  
[SCT-132](https://hackney.atlassian.net/browse/SCT-132)
- ~Have you added any new third-party libraries?~
- ~Are any new environment variables or configuration values needed?~
- ~Anything else in this PR that isn't covered by the what/why?~
=> fix(SCT-132): updates to the CFS warning note form

pages/maintenance.tsx, serverless.yml
Maintenance mode test in staging
=> SCT-30 - Maintenance mode test

components/Layout/Header/Header.tsx, next.config.js, pages/maintenance.tsx, serverless.yml
Test with hardcoded values and navigations redirects
=> Maintenance staging test

.circleci/config.yml
=> Update CircleCI config to temporarily disable staging deployment

.circleci/config.yml
=> Fix sequencing of CircleCI jobs

.circleci/config.yml
=> SCT-303 - Restoring CircleCI config

.circleci/config.yml
=> Restoring staging

cypress/integration/search_for_person.ts, pages/api/residents/index.ts
Putting this back on staging for Felix to test
=> feat(SCT-179): show all records in search results

cypress/integration/search_for_person.ts, pages/api/residents/index.ts
Reverts LBHackney-IT/lbh-social-care-frontend#410
=> revert: "feat(SCT-179): show all records in search results"

cypress/integration/search_for_person.ts, pages/api/residents/index.ts
Reverts LBHackney-IT/lbh-social-care-frontend#411
[Ticket](https://hackney.atlassian.net/browse/SCT-179)
If approved we will look to deploy this to production on Tuesday (01/06/2021)
We can merge this branch into `main` earlier so the changes appear in our staging environment for UAT.
We just need to be careful when deploying our frontend to prod we don't release this pre-approval.
=> Revert "revert: "feat(SCT-179): show all records in search results""

factories/relationships.ts, lib/relationships.spec.ts
[Ticket link](https://hackney.atlassian.net/browse/SCT-204)
**What**  
Added API calls tests for Relationships
**Why**  
Making sure the communication works correctly
Removed unused import from Relationships mocked data
=> SCT-204  - Write front end views for displaying relationships

lib/submissions.spec.ts, lib/submissions.ts
This is a copy of #432  without merge conflicts.
=> connect fe backend to api

data/flexibleForms/review3C.ts
changes to the schema of form review 3c
=> update review3c content

components/Steps/PersonConfirmation.tsx, components/Steps/PersonLinkConfirmation.tsx, components/Steps/ReviewWarningNoteConfirmation.tsx
**What**  
Change button redirect from Dashboard to search
**Why**  
The change was omitted when Dashboard became the landing page.
=> change redirect from 'Return to search' button

components/Steps/ReviewWarningNoteConfirmation.spec.tsx, components/Steps/ReviewWarningNoteConfirmation.tsx, components/Steps/__snapshots__/ReviewWarningNoteConfirmation.spec.tsx.snap, components/WarningNote/WarningNoteRecap/__snapshots__/WarningNoteRecap.spec.tsx.snap, data/forms/warning-note-review.tsx, data/forms/warning-note.tsx
**What**  
A handful of copy errors were present on both warning notes forms, this fixes those!
**Why**  
[SCT-544](https://hackney.atlassian.net/browse/SCT-544)
=> fix(SCT-544): A handful of copy changes

lib/residents.spec.ts, lib/residents.ts, pages/api/residents/[id]/index.ts, pages/api/submissions/[id]/index.ts, pages/api/submissions/[id]/steps/[stepId].tsx
see https://hackit-lbh.slack.com/archives/C021Q88C953/p1622725373088900
=> make it easier to get a resident by id

data/flexibleForms/allForms.ts, data/flexibleForms/forms.types.ts, lib/submissions.spec.ts, lib/submissions.ts, pages/api/submissions/[id]/index.ts, pages/people/[id]/submissions/[submissionId].tsx, pages/submissions/[id]/index.tsx, pages/submissions/[id]/steps/[stepId].tsx
final tweaks needed to make the new form builder and submissions engine demoable end to end.
go to `/submissions/new` to kick off a submission
go to `/people/:id/submission/:submissionId` to review a finished submission
this _does not_ actually start redirecting users to the new form builder. so it's totally safe to launch. that will come in a few days.
=> it works and we love that it works

components/PersonWidget/PersonWidget.spec.tsx, components/PersonWidget/PersonWidget.tsx, components/PersonWidget/__snapshots__/PersonWidget.spec.tsx.snap, factories/residents.ts, lib/residents.spec.ts, types.ts
**What**  
After a change to the back end to send the addresses array, the Person Widget was updated to display the correct postcode and address info
**Why**  
Address and Postcode were not displaying in Person Widget 
Adapted types file and resident Factory to contain addresses array.
Added a new test for handling addresses.
=> refactor types to display addresses array and add tests.

components/pages/warning-notes/AddWarningNoteForm/AddWarningNoteForm.spec.tsx, components/pages/warning-notes/ReviewWarningNoteForm/ReviewWarningNoteForm.spec.tsx, components/pages/warning-notes/ReviewWarningNoteForm/ReviewWarningNoteForm.tsx, components/pages/warning-notes/ReviewWarningNoteForm/__snapshots__/ReviewWarningNoteForm.spec.tsx.snap, data/forms/warning-note-review.tsx, pages/people/[id]/warning-notes/[warningNoteId]/[[...stepId]].tsx, test/helpers.tsx
**What**  
* Moves some of the helpers added for the `<AddWarningNoteForm />` tests into a shared test helpers file
* Refactors the 'review warning note' form into a separate component
* Adds a small suite of automation tests for the new `<ReviewWarningNoteForm />` component
**Why**  
[SCT-599](https://hackney.atlassian.net/browse/SCT-599)
=> feat(SCT-599): 'Review warning note' automation tests

components/FlexibleForms/StepForm.tsx
- form submit button now has a type attribute to help older browsers
- autosave delay is now 2 seconds again
- an invalid form, once validated, _won't_ now auto-return to the task list, like it was before
=> flexible form cleanup and bug fixes

components/FlexibleForms/StepForm.tsx, pages/_document.tsx
[Link to ticket](https://hackney.atlassian.net/browse/SCT-645)
**What**  
Added google tracking script in head and body tag
**Why**  
so we can start tracking events.
=> SCT-645 Install google tag manager code to website 

components/Layout/Header/Header.spec.tsx, components/Layout/Header/Header.tsx, components/Layout/Header/__snapshots__/Header.spec.tsx.snap, lib/permissions.ts
**What**  
The "Manage workers" menu item wasn't showing for admins (only devs). This fixes that!
**Why**  
[SCT-251](https://hackney.atlassian.net/browse/SCT-251)
=> fix(SCT-251): show 'manage workers' menu item for admins

components/pages/warning-notes/ReviewWarningNoteForm/ReviewWarningNoteForm.spec.tsx
This adds a test to cover the expected behaviour when ending a warning note.
Renewing or ending a warning note all fall under the `<ReviewWarningNoteForm />` component.
=> Feat(SCT-600, SCT-552): Add test for ending a warning note

.circleci/config.yml, .release-it.json, package.json, yarn.lock
BREAKING CHANGE
**What**  
(It's not a breaking change, but this _should_ bump us to `v1.0.0`!)
This PR introduces some scripts that run in CircleCI to automatically generate release notes, and tag releases in GitHub. This gives us a couple of benefits:
1. The draft release generated on merge to `main` will allow us to see what is ready to release in one place
2. Once a release to production is made, that release will be marked as "published" and a version increment will be automatically applied to our `package.json` file. The full changelog will be attached to that release in GitHub, so we will know what was released 🎉 
3. We can always see when the last release was. When there is an active production incident, it will be easy to see when the last production change was.
**Future …
=> feat(SCT-724): add an automated release documentation tool

data/roles.ts
**What**  
A handful of requests have come in to introduce new roles to the system, this does just that!
**Why**  
[SCT-605](https://hackney.atlassian.net/browse/SCT-605), [SCT-720](https://hackney.atlassian.net/browse/SCT-720)
=> feat(SCT-605, SCT-720): add new roles

components/AddForm/AddForm.tsx
**What**  
Face overview form can be seen in prod by any user, this should not be the case yet!
Hide form behind the user being a dev or admin.
=> Bug(): Hide flexible forms beind admin or dev permissions

data/flexibleForms/faceOverview.ts
this improves the face overview form by:
- adding many more conditional questions, including questions with more than one AND condition
- shortening and re-wording questions hints for flow and clarity
- re-organising the order of steps to better fit the task list pattern
- converting field and step `id`s from kebab case to normal sentence case
=> feature: improve face overview form

components/AddForm/AddForm.spec.tsx, data/flexibleForms/sgAdultConcern.ts, data/flexibleForms/sgAdultManagerDecisionConcern.ts, data/googleForms/adultForms.ts
Reverts LBHackney-IT/lbh-social-care-frontend#552
=> Revert "feat: deploy safeguarding forms"

pages/api/submissions/[id]/index.ts
**What**  
This PR fixes the issue with the approve email not sending or sending late once a form has been requested to be approved.
**Why**  
To allow the approve email to be sent on time
=> Fix: Gov notify approve email sending

pages/api/submissions/[id]/index.ts
**What**  
Resolve a bug where notify was being called for all PATCH requests and not just finishing a submission
=> Bug: Notify firing from patching residents

components/Cases/Cases.tsx, components/Cases/__snapshots__/Cases.spec.tsx.snap
the button has been replaced, the url it links to no longer exists
=> fix: remove dead button

components/pages/people/relationships/view/Relationships.spec.tsx, components/pages/people/relationships/view/Relationships.tsx, factories/relationships.ts, lib/relationships.spec.ts
**What**  
Refactor `components/pages/people/relationships/view/Relationships.spec.tsx` to move factory building into the test file and renamed test descriptions.
**Why**
So that the set up required for a test and what the test is doing is clearer.
=> refactor(SCT-481): move factory building into test file

components/Layout/Footer/Footer.tsx, components/Layout/__snapshots__/index.spec.tsx.snap
Tiny change to remove /home from the link to the roadmap in the footer.
=> update footer link

data/roles.ts
**What**  
Adds a new role for the DCS Annual Care Package Review.
**Why**  
[SCT-911](https://hackney.atlassian.net/browse/SCT-911)
=> feat(SCT-911): add DCS Level 1 Care Package role for CFS

components/pages/people/relationships/view/Relationships.spec.tsx, components/pages/people/relationships/view/Relationships.tsx, features.ts
**What**  
Enable adding and removing relationships by removing feature flags
**Why**  
To enable features on production
=> feat(SCT-26, SCT-27): Enable add and delete relationships

components/Cases/CaseLink.spec.tsx, components/Cases/__snapshots__/CaseLink.spec.tsx.snap, components/FlexibleForms/FlexibleFields.spec.tsx, components/FlexibleForms/FlexibleFields.tsx, components/FlexibleForms/StepForm.tsx, components/SubmissionsTable/SubmissionPanel.spec.tsx, data/flexibleForms/adultCaseNote.ts, data/flexibleForms/childCaseNote.ts, data/flexibleForms/faceOverview.ts, data/flexibleForms/foo.ts, data/flexibleForms/forms.types.ts, data/flexibleForms/review3C.ts, data/flexibleForms/sgAdultConcern.ts, data/flexibleForms/sgAdultManagerDecisionConcern.ts, lib/notify.spec.ts, lib/validators.spec.ts, lib/validators.ts
https://hackney.atlassian.net/browse/SCT-857
solves the problem by:
- removing the separate `validateConditionalFields` and combine the logic into our main `generateFlexibleSchema` function
- extract `applyRequired` into its own function to stop duplication
- make every form have `conditions: Condition[]` rather than allowing some to be a plain object
- add some new tests to specifically cover the buggy behaviour
**the only interesting stuff here is in `lib/validators.ts`**
=> fix(sct-857): auto save stuck on hidden conditionals

.circleci/config.yml, serverless.yml
**What**  
Changed CircleCI and Serverless to deploy the new FE lambda in mosaic-production in parallel with production APIs
**Why**  
To change where the lambda lives
=> SCT-462 - FE Lambda migration

data/flexibleForms/childCaseNote.ts
**What**  
this is to reintroduce two questions that were accidentally deleted:
- Were the child/children seen?
- Were the child/children seen alone?
**Why**  
these questions should be present in the form when needed
N/A
=> fix(SCT-984): reintroducing two questions 

data/flexibleForms/childCaseNote.ts
**What**  
[Ticket](https://hackney.atlassian.net/browse/SCT-1080)
Just need to change the text for a couple of questions based on feedback.
Also make sure that we now capture the date of event for the child case note.
=> Fix(SCT-1080): Change content of questions in cfs case notes form

data/flexibleForms/adultCaseNote.ts, data/flexibleForms/childCaseNote.ts, data/flexibleForms/forms.types.ts, lib/validators.ts, package.json
**What**  
This PR is about not allowing for case notes to be created for a future date.
**Why**  
Case notes are reflections of something that has already happened.
No
No
N/A
=> Fix (Sct 994): Case notes date validation

ci-scripts/delete-draft-github-releases.spec.js, components/ApprovalWidget/RejectDialog.spec.tsx, components/ApprovalWidget/RejectDialog.tsx, components/Cases/CasesTable.tsx, components/DuplicateWarningPanel/DuplicateWarningPanel.spec.tsx, components/ErrorBoundary/ErrorBoundary.spec.tsx, components/FlexibleAnswers/FlexibleAnswers.spec.tsx, components/NewPersonView/UnfinishedSubmissions.spec.tsx, components/PrintableForm/PrintableForm.spec.tsx, components/PrintableForm/PrintableForm.tsx, components/RevisionTimeline/MiniSubmissionTimeline.spec.tsx, components/pages/people/relationships/view/Relationships.spec.tsx, contexts/autosaveContext.spec.tsx, lib/utils.spec.ts, test/helpers.tsx, utils/api/relationships.spec.ts, utils/api/relationships.ts, utils/date.spec.ts
**What**  
When running the test suite there are a number of errors, warnings and  unexpected output. On investigation I found a number of issues:
* a number of async describe blocks.
* non-unique react mapped keys in mocked data.
* key props missing from some nested components.
* some unneeded debug logging in tests.
* parse date test fails on MacOS.
* promises not waited on, resulting in some tests never being executed or logging after execution
* error boundary tests with logging to cli
**Why**  
This can be a sign of smelly tests, so was worth investigating to ensure the tests were doing what we expect.
* No third party libraries added.
* Added a new helper method `getByTextIgnoringTags` which will get text on a page that is split across several html tags.
=> Fix (SCT-1086): Clean up test suit

components/Cases/CaseLink.spec.tsx, components/Cases/CaseLink.tsx, components/Cases/CasesTable.tsx, components/Cases/__snapshots__/CaseLink.spec.tsx.snap, components/NewPersonView/EventLink.tsx, data/flexibleForms/mapFormIdsToDisplayName.ts
**What**  
Include the case note title in the case records
**Why**  
Makes it easier for workers to find the form they want
=> Bug(SCT-1088): Case note title not displaying correctly

components/CaseStatus/CaseStatusView.spec.tsx, components/CaseStatus/CaseStatusView.tsx, components/NewPersonView/Layout.spec.tsx, components/NewPersonView/Layout.tsx, pages/people/[id]/index.tsx
**What**  
- Added necessary styling bits for displaying case status types in Person view.
- Test for Case Status Types adjusted
- Tests for Layout adjusted to include a FeatureFlag provider (necessary for the component)
**Why**  
It was not displaying correctly and in the incorrect section.
=> fix(SCT-962): Added styles for status type view

data/roles.ts
**What**  
Introduces a new role for CFS users, "Service Manager".
=> feat: Add 'Service Manager' role to CFS

components/CaseStatus/CaseStatusView.spec.tsx, components/CaseStatus/CaseStatusView.tsx, factories/caseStatus.ts, lib/caseStatus.ts, types.ts
**What**  
The Backend response for Case Status changed.
Frontend has been adjusted accordingly
**Why**  
To match the Backend response
Tests, factories and types changed / updated
=> feat(SCT-1111): Case status response structure change

components/CaseStatus/AddCaseStatusForm/AddCaseStatusForm.tsx
**What**  
Fixed a null pointer exception
**Why**  
A null pointer exception was getting triggered by the Add case status page
=> fix(SCT-1024): Added null check to Case Status

components/NewPersonView/Layout.tsx
**What**  
The feature flag didn't work properly, so I'm removing the code that shouldn't be in the release
**Why**  
I was expecting the feature flag to not execute the code, but it looks like it's doing it regardless.
I'll re-introduce after checking what went wrong
=> fix: Removed feature flagged part that's not working

components/NewPersonView/Layout.tsx
**What**  
Case status feature flag failed yesterday as I put some logic in a `<ConditionalFeature>` block, expecting it to not be executed.
This logic now has been moved and adjusted with an appropriate check (by using the `isFeatureActive` function)
**Why**  
Added a better feature flag check for the Case Status logic.
=> fix(SCT-1216): Case status feature flag

features.ts, lib/validators.ts
**What**  
case-status feature flag expired, updated the expiry date to go until the end of the year
=> fix: Case Status feature flag expiry date 

utils/contentSecurity.spec.ts, utils/contentSecurity.ts
**What**  
- Added CSP directive `'sha256-TGjSkcFoVCRdq4Hp3hcETnPc9cikdBGvkz/08Bjzy0I='` for the `style-src-elem`element
- Added `in.hotjar.com` to the `connect-src` directive 
- Update tests
**Why**  
Added CSP string to `contentSecurity.ts`
=> fix: update content security policy

components/CaseStatus/UpdateCaseStatusForm/UpdateCaseStatusForm.spec.tsx
**What**  
FIxed the non-working test
**Why**  
The async function that fired the event for the test was not behaving properly:
It was running correctly for a while both in circleci and in the local environment, then it suddenly stopped working.
Running the code in a synchronous way makes the test run correctly.
=> fix: Case Status failing test

components/MashDashboard/MashDashboard.tsx, components/SuccessSummary/SuccessSummary.module.scss, components/SuccessSummary/SuccessSummary.tsx, pages/mash-referral/[id]/screening-decision.tsx
**What**  
On completion of the screening decision form a user is redirected back to team-assignments page and a confirmation/s is shown to indicate that the form was submitted successfully.
=> feat(SCT-1443): Confirmation on screening action

components/SuccessSummary/SuccessSummary.spec.tsx, components/SuccessSummary/SuccessSummary.tsx
**What**  
Test SuccessSummary component renders passed data correctly.
**Why**  
Improves confidence in code being bug free.
=> feat: test success summary component

components/NewPersonView/Layout.spec.tsx, components/NewPersonView/Layout.tsx
accounting for the new planner becoming the default view
=> chore: update resident's workflow link

components/NewPersonView/PersonHistory.tsx
**What**  
This PR standardise two parameter sent to the /case endpoint
**Why**  
The parameter sent by the frontend are not standard.
=> fix: Case note parameter name change

lib/mashReferral.ts
**What**  
The reset button pointed to a non existent endpoint
**Why**  
This PR corrects the issue 
=> fix(SCT-1560): corrected link to reset button

.circleci/config.yml
**What**  
update to node executor in config.yml
=> feat(SCT-1572): update node executor for circleci

serverless.yml
**What**  
Deployment package size is still too large, attempting to remove unnecessary files
=> feat(SCT-1279): exclude build cache from layer and from function

serverless.yml
**What**  
Changed the way we include/exclude files in the serverless configuration.
**Why**  
We cannot use include/exclude together with patterns, so we opted for using only patterns
=> chore: Serverless config switch from include to patterns

utils/auth.ts
**What**  
This PR fixes the Internal Server Error when the token expires
**Why**
=> fix: Expired session token error

data/roles.ts
**What**  
Now that Tuomo has set up a new Customer Service team in the social care case viewer API, we need to add new customer service officer role for workers in that team
=> feat(SCT-1710): add customer service officer role 

ci-scripts/validate-pr-title.spec.js, components/FlexibleForms/FlexibleFields.tsx, components/MashCards/ContactCard.tsx, components/MashCards/FinalDecisionCard.tsx, components/MashCards/InitialDecisionCard.tsx, components/MashCards/ScreeningCard.tsx, components/MashForms/ContactForm.spec.tsx, components/MashForms/FinalDecisionForm.spec.tsx, components/MashForms/InitialDecisionForm.spec.tsx, components/MashForms/ScreeningDecisionForm.spec.tsx, components/MashForms/ScreeningDecisionForm.tsx, components/NewPersonView/UnfinishedSubmissions.spec.tsx, components/ResidentPage/CustomAddressEditor.spec.tsx, data/flexibleForms/caseStatus/caseStatus.ts, data/flexibleForms/forms.types.ts, lib/validators.spec.ts, lib/validators.ts
**What**  
Changes to reduce the number of errors on the console in unit tests. This also introduces fixes to a number of tests with issues.
**Why**  
Because seeing warnings and errors in tests is a code smell. This also meant I found missing and incomplete tests.
- Have you added any new third-party libraries? ❌
- Are any new environment variables or configuration values needed? ❌
- Anything else in this PR that isn't covered by the what/why? ❌
=> fix: unit test errors

pages/people/[id]/index.tsx
**What**  
Remove preview banner form person page
**Why**  
Attempting to resolve error has occurred message
=> fix: Remove preview banner

components/ResidentPage/InlineEditor.spec.tsx, components/ResidentPage/InlineEditor.tsx, pages/api/residents/[id]/index.ts
**What**  
Change the endpoint in the frontend to point to the backend endpoint
**Why**  
The frontend was pointing back to the frontend endpoint incorrectly
=> fix: Change endpoint

components/ResidentPage/CustomAddressEditor.tsx, components/ResidentPage/CustomGPDetailsEditor.tsx, components/ResidentPage/CustomKeyContactsEditor.tsx, components/ResidentPage/CustomPhoneNumberEditor.tsx, components/ResidentPage/InlineEditor.tsx
it's annoying people more than it's helping, so let's not
only affects new resident view + inline editing
=> chore: don't warn on unsaved changes

pages/residents/[id]/activity.tsx, pagesTest/residents/[id]/activity.spec.tsx
satisfies https://trello.com/c/JpPAROOC/913-items-in-activity-list-should-link-to-page-content-where-appropriate
=> chore: activity is clickable

components/Allocations/AddAllocation/AddAllocation.tsx, components/PriorityRating/PriorityRating.tsx, cypress/integration/allocate_worker.ts, cypress/integration/team_allocations.ts, pages/residents/[id]/allocations.tsx
**What**  
Added E2E tests for the new Allocation flow
The tests will:
-Add a Team / Worker allocation
-Change the priority level
-Remove the Worker allocation
-Remove the Team allocation
The user on which the test will point is the ID `7`, the team will be `testing-team`
+ Added styles and ID for easier testing
**Why**  
This ensures that the feature works as intended
- Have you added any new third-party libraries? X
=> feat: Allocations E2E tests

components/FlexibleAnswers/FlexibleAnswers.tsx, components/ResidentPage/CaseNoteDialog.spec.tsx, components/ResidentPage/CaseNoteDialog.tsx, components/ResidentPage/CaseNoteTile.spec.tsx, components/ResidentPage/CaseNoteTile.tsx, lib/formatters.spec.ts, lib/formatters.ts
**What**  
Refactored the way that replacing special characters in case notes work. There is a new formatter function that has been added and this is then used in the various case note scenarios.
**Why**  
Previous work only covered removing special characters from historical case notes, this should work for all case notes
=> fix: Fix case note tags

components/TeamPage/Layout.tsx, components/TeamPage/TeamWorkerList/TeamWorkerList.tsx, components/WorkerView/WorkerAllocations/WorkerAllocations.tsx, pages/index.tsx
**What**  
- Removed additional space after the ‘hours ago’ and ‘)’ in the team members accordion 
- Reduced the padding under ‘my work’ so it’s consistent with the other sections e.g. when you click on a specific team.
- Aligned the breadcrumb/content to the nav bar (my work, team, workflows)
- Added spinner when loading "my work" page
=> fix(SCT-1822): More allocations UI fixes

pages/index.tsx, pages/workers/index.tsx
**What**  
This pages fixes a bug for the main page if you're not a worker 
and
adds back the  worker/index page deleted by mistake 
**Why**  
Those errors were encountered in the live production deployment
=> fix: current prod bugs

pages/residents/[id]/index.tsx
**What**  
Rename of a field in the resident details view
**Why**  
This change was requested to make it clearer that this could be a team
- Have you added any new third-party libraries? X
=> fix: Rename housing officer field

components/TeamPage/TeamAllocationsList/TeamAllocationsList.spec.tsx, components/TeamPage/TeamAllocationsList/TeamAllocationsList.tsx, components/WorkerView/WorkerAllocations/WorkerAllocations.spec.tsx, components/WorkerView/WorkerAllocations/WorkerAllocations.tsx, pages/residents/[id]/index.tsx, pagesTest/residents/id/index.spec.tsx, types.ts
**What**  
This PR adds the necessary bits to display and set the review date for residents
=> feat (SCT-1838): Review date

features.ts
**What**  
Update expired feature flag reminders
**Why**  
To pass linting rules
=> feat: Update expiry dates in feature flags
